### ISSUE TITLE
SyntaxError: Duplicate data property in object literal not allowed in strict mode

### ISSUE THREAD

**Issue by widder** [Schmavery/facebook-chat-api#119]
```
info Logging in... 
info Logged in 

/home/user/node_modules/facebook-chat-api/src/getFriendsList.js:15
  5: 'mixed_plural',
  ^
ERR! Error in login: SyntaxError: Duplicate data property in object literal not allowed in strict mode
ERR! Error in login:     at Module._compile (module.js:439:25)
ERR! Error in login:     at Object.Module._extensions..js (module.js:474:10)
ERR! Error in login:     at Module.load (module.js:356:32)
ERR! Error in login:     at Function.Module._load (module.js:312:12)
ERR! Error in login:     at Module.require (module.js:364:17)
ERR! Error in login:     at require (module.js:380:17)
ERR! Error in login:     at /home/user/node_modules/facebook-chat-api/index.js:97:14
ERR! Error in login:     at Array.map (native)
ERR! Error in login:     at buildAPI (/home/user/node_modules/facebook-chat-api/index.js:96:16)
ERR! Error in login:     at mainPromise.then.then.error (/home/user/node_modules/facebook-chat-api/index.js:299:19)
ERR! Error in login:     at tryCatcher (/home/user/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in login:     at Promise._settlePromiseFromHandler (/home/user/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in login:     at Promise._settlePromiseAt (/home/user/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in login:     at Async._drainQueue (/home/user/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:128:12)
ERR! Error in login:     at Async._drainQueues (/home/user/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in login:     at Async.drainQueues (/home/user/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in login:  [SyntaxError: Duplicate data property in object literal not allowed in strict mode]
[SyntaxError: Duplicate data property in object literal not allowed in strict mode]
```

**Comment by Schmavery** [comment]
Fixed by #120
