### ISSUE TITLE
npm test errors

### ISSUE THREAD

**Issue by petr-stety-stetka** [Schmavery/facebook-chat-api#123]
When I run `npm test` command I get this errors: :(
Yes, I created file test-config.json according to instructions.
Can you help me, please?
```
> facebook-chat-api@1.0.4 test /home/stety/node_modules/facebook-chat-api
> mocha



  Login As Page:

/home/stety/node_modules/facebook-chat-api/src/getFriendsList.js:15
  5: 'mixed_plural',
  ^
    1) "before all" hook

  Login:
    2) "before all" hook


  0 passing (7s)
  2 failing

  1) Login As Page: "before all" hook:
     SyntaxError: Duplicate data property in object literal not allowed in strict mode
      at index.js:97:14
      at Array.map (native)
      at buildAPI (index.js:96:16)
      at mainPromise.then.then.error (index.js:299:19)
      at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
      at Async._drainQueue (node_modules/bluebird/js/main/async.js:128:12)
      at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
      at Async.drainQueues (node_modules/bluebird/js/main/async.js:15:14)

  2) Login: "before all" hook:
     SyntaxError: Duplicate data property in object literal not allowed in strict mode
      at index.js:97:14
      at Array.map (native)
      at buildAPI (index.js:96:16)
      at mainPromise.then.then.error (index.js:299:19)
      at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
      at Async._drainQueue (node_modules/bluebird/js/main/async.js:128:12)
      at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
      at Async.drainQueues (node_modules/bluebird/js/main/async.js:15:14)



npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0```

**Comment by petr-stety-stetka** [comment]
What mean this error, please?
`[SyntaxError: Duplicate data property in object literal not allowed in strict mode`

**Comment by Schmavery** [comment]
This error refers to a duplicate key in an object.  For example:
```js
{
   key1 : val1,
   key1 : val2,
   key2 : val3
}
```
Here `key1` is seen twice.  This used to be the case in a utils function in our code.  This has since been fixed.  I would recommend updating to the newest code on github and trying again.

**Comment by petr-stety-stetka** [comment]
The latest code from github works, thank you.  :)
