### ISSUE TITLE
getting error on sending message.

### ISSUE THREAD

**Issue by ilhamiarie** [Schmavery/facebook-chat-api#129]
hai @Schmavery, I had just encountered an error when sending a message . 

Unhandled rejection TypeError: Cannot read property 'threadID' of undefined
    at callback (E:\netbeans 81\Add Otomax Facebook\main.js:36:43)
    at E:\netbeans 81\Add Otomax Facebook\node_modules\facebook-chat-api\src\listen.js:244:7
    at tryCatcher (E:\netbeans 81\Add Otomax Facebook\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (E:\netbeans 81\Add Otomax Facebook\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (E:\netbeans 81\Add Otomax Facebook\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (E:\netbeans 81\Add Otomax Facebook\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (E:\netbeans 81\Add Otomax Facebook\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (E:\netbeans 81\Add Otomax Facebook\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\netbeans 81\Add Otomax Facebook\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:384:17)
    at Function.module.exports.loopWhile (E:\netbeans 81\Add Otomax Facebook\node_modules\deasync\index.js:64:21)
    at Function.sleep (E:\netbeans 81\Add Otomax Facebook\node_modules\deasync\index.js:36:18)
    at readOutbox (E:\netbeans 81\Add Otomax Facebook\main.js:77:17)
    at Object.<anonymous> (E:\netbeans 81\Add Otomax Facebook\main.js:68:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)

**Comment by Schmavery** [comment]
Please post a sample program that exhibits this behavior so that we can help find the issue. :smile:

**Comment by bsansouci** [comment]
Looking at the stack trace it seems like the error is thrown because your code's accessing`threadID` of some undefined object. My guess is that you didn't check the error passed to the callback, which in this case would be set (and therefore the 2nd argument to the callback would be undefined). Can you check?

**Comment by Schmavery** [comment]
I'm going to close this because a fair number of issues have been solved in sendMessage lately.  Please reopen with more details if this continues to be a problem for you.
