### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by kshvmdn** [Schmavery/facebook-chat-api#151]
Seems as if thread can't be found when there's a symbol in title. 

Error with stacktrace:
```
Unhandled rejection TypeError: Cannot read property 'filter' of undefined
    at ../node_modules/facebook-chat-api/src/listen.js:169:40
    at ../node_modules/facebook-chat-api/src/searchForThread.js:27:18
    at tryCatcher (../node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (../node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (../node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (../node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (../node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (../node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (../node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

Come across error when `threadName` contains special symbols. Shouldn't be hard to reproduce, try with `§` in chat name.

**Comment by kshvmdn** [comment]
Only happening when group chat has more than 4 participants.

**Comment by kshvmdn** [comment]
Fixed in https://github.com/Schmavery/facebook-chat-api/commit/ca9beae7c26dbd626e840a8c5c5f666839be8dc4, my mistake.
