### ISSUE TITLE
Error in uploadAttachment when sending images with certain aspect ratios

### ISSUE THREAD

**Issue by jobbogamer** [Schmavery/facebook-chat-api#152]
I'm attempting to send images as attachments by opening an image URL as a stream, then passing that to the send function. Most images work fine, but if I use an image that has _approximately_ a 2:1 aspect ratio, I get an error:

```
ERR! Error in uploadAttachment Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
ERR! Error in uploadAttachment     at node_modules/facebook-chat-api/utils.js:396:40
ERR! Error in uploadAttachment     at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in uploadAttachment     at Function.Promise.attempt.Promise.try (node_modules/bluebird/js/main/method.js:31:24)
ERR! Error in uploadAttachment     at parseAndCheckLogin (node_modules/facebook-chat-api/utils.js:395:22)
ERR! Error in uploadAttachment     at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in uploadAttachment     at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in uploadAttachment     at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in uploadAttachment     at Promise._settlePromises (node_modules/bluebird/js/main/promise.js:697:14)
ERR! Error in uploadAttachment     at Async._drainQueue (node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in uploadAttachment     at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in uploadAttachment     at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in uploadAttachment     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in uploadAttachment  [Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.]
```

If I send any other aspect ratio, it works and uploads perfectly.

**Comment by bsansouci** [comment]
We had a bunch of problems with sending images in the past. Can you check if you can send that specific image from the browser (on `www.facebook.com`)?
Can you add `console.log(data.body)` **above** [this line](https://github.com/Schmavery/facebook-chat-api/blob/bd056e4cd1f623e2e7ec1b92e241041358352103/utils.js#L505) and paste the prints right before it throws that error.

**Comment by Schmavery** [comment]
@bsansouci We've made a number of changes without pushing to npm.  I can do that when I get home today.
@jobbogamer Are you trying to send this as a page?  It would also be cool to know what version of the API you're using.  Can you upload an example of a picture that fails?

**Comment by jobbogamer** [comment]
OK, so the image is found here: https://plot.ly/~jobbogamer/17.png

This is sending as a regular account, not a page. I can send the image perfectly fine using the browser. Hopefully the below will help a bit… 

I'm doing:
```
https.get(url, function (res) {
    var message = {
        body: 'Hello, world!',
        attachment: res
    };

    api.send(message, ...);
```

This massive wall of text is everything that got spat out by adding a `console.log()`:

```
for (;;);{"__ar":1,"payload":{"profiles":{"1405454336":{"id":"1405454336","name":"Josh Asch","firstName":"Josh","vanity":"jobbogamer","thumbSrc":"https:\/\/scontent-lhr3-1.xx.fbcdn.net\/hprofile-frc3\/v\/t1.0-1\/p32x32\/1381587_10202255503494752_703002890_n.jpg?oh=bc9fb840ee43b5503e77f88550c543ec&oe=573E9015","uri":"https:\/\/www.facebook.com\/jobbogamer","gender":2,"type":"friend","is_friend":true,"mThumbSrcSmall":null,"mThumbSrcLarge":null,"dir":null,"searchTokens":["Asch","Josh"],"alternateName":"","is_nonfriend_messenger_contact":false}}},"jsmods":{"require":[["Cookie","setIfFirstPartyContext",[],["_js_datr","KWCfVmRn9ljccbZe6yQFSc5c",63072000000,"\/",false],[]]]},"bootloadable":{},"ixData":{},"lid":"6241813339704945110"}
for (;;);{"__ar":1,"payload":[],"jsmods":{"require":[["Cookie","setIfFirstPartyContext",[],["_js_datr","KWCfVsYMDX1NW-mTjZ0glX1l",63072000000,"\/",false],[]]]},"bootloadable":{},"ixData":{},"lid":"6241813337779021582"}
for (;;); {"t":"msg","seq":10,"u":100010714721973,"ms":[{"folder":"inbox","thread_row":"","is_unread":false,"sequence_id":29156,"msg_body":"","new_participants":"","unread_counts":{},"html":"","type":"messaging","message":{"attachments":[],"ranges":[],"share_map":[],"subject":null,"mercury_author_id":"fbid:100010714721973","timestamp_relative":null,"mid":"mid.1453285417240:08c97e24dd7637ea44","sender_name":"Marcus Zuckerbot","has_attachment":false,"source":"source:chat:web","body":"No command matching 'thing'.","tid":null,"mercury_source_tags":["source:chat"],"timestamp_datetime":null,"mercury_author_email":"100010714721973@facebook.com","replyActionType":0,"other_user_fbid":1405454336,"timestamp":1453285417294,"timestamp_time_passed":null,"offline_threading_id":"6095520837962482454","mercury_source":"source:chat:web","group_thread_info":null,"html_body":"","forward":0,"threading_id":"<1453285417070:0-be3f22431902c48b@mail.projektitan.com>","timestamp_absolute":null,"short_source":1,"tags":"source:chat:web,sent,inbox,cg-enabled","is_spoof_warning":false,"ephemeral_ttl_mode":0,"sender":"100010714721973@facebook.com","is_unread":false,"api_tags":["sent","inbox","read","source:chat"],"sender_fbid":100010714721973,"attachmentIds":[],"prev_last_visible_action_id":-1,"attachment_map":[]},"event":"deliver"}]}
for (;;);{"__ar":1,"payload":{"actions":[{"thread_id":null,"thread_fbid":null,"other_user_fbid":"1405454336","action_id":null,"action_type":"ma-type:update-action-id"}],"payload_source":"server_change_read_status"},"jsmods":{"require":[["Cookie","setIfFirstPartyContext",[],["_js_datr","KWCfVt92acw6eIghg_38Ute5",63072000000,"\/",false],[]]]},"bootloadable":{},"ixData":{},"lid":"6241813338439570005"}
for (;;); {"t":"msg","seq":13,"u":100010714721973,"ms":[{"event":"read","tids":["mid.1449082442991:c061887633e309e275"],"thread_fbids":[],"other_user_fbids":[1405454336],"chat_ids":[1405454336],"mark_as_read":true,"folder_info":[],"timestamp":1453285416720,"realtime_viewer_fbid":100010714721973,"type":"messaging"},{"unread":0,"unseen":0,"seen_timestamp":0,"realtime_viewer_fbid":100010714721973,"type":"inbox"},{"sequence_id":29158,"delivered":true,"type":"messaging","event":"delivery_receipt","other_user_fbid":1405454336,"timestamp":1453285417294}]}
for (;;); {"t":"msg","seq":14,"u":100010714721973,"ms":[{"event":"read","tids":["mid.1449082442991:c061887633e309e275"],"thread_fbids":[],"other_user_fbids":[1405454336],"chat_ids":[1405454336],"mark_as_read":true,"folder_info":[],"timestamp":1453285416720,"realtime_viewer_fbid":100010714721973,"type":"messaging"}]}

<!DOCTYPE html>
<html lang="en" id="facebook">
  <head>
    <title>Facebook | Error</title>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="cache-control" content="no-store">
    <meta http-equiv="cache-control" content="max-age=0">
    <meta http-equiv="expires" content="-1">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="noindex,nofollow">
    <style>
      html, body {
        color: #141823;
        background-color: #e9eaed;
        font-family: Helvetica, Lucida Grande, Arial,
                     Tahoma, Verdana, sans-serif;
        margin: 0;
        padding: 0;
        text-align: center;
      }

      #header {
        height: 30px;
        padding-bottom: 10px;
        padding-top: 10px;
        text-align: center;
      }

      #icon {
        width: 30px;
      }

      h1 {
        font-size: 18px;
      }

      p {
        font-size: 13px;
      }

      #footer {
        border-top: 1px solid #ddd;
        color: #9197a3;
        font-size: 12px;
        padding: 5px 8px 6px 0;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <a href="//www.facebook.com/">
        <img id="icon" src="//static.xx.fbcdn.net/images/logos/facebook_2x.png" />
      </a>
    </div>
    <div id="core">
      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
      <p id="back-link">
        <a id="back" href="//www.facebook.com/">Go Back</a>
      </p>
      <div id="footer">
        Facebook
        <span id="copyright">
          &copy; 2016
        </span>
        <span id="help-link">
          &#183;
          <a id="help" href="//www.facebook.com/help/">Help Center</a>
        </span>
      </div>
    </div>
    <script>
      document.getElementById('back').onclick = function() {
        if (history.length > 1) {
          history.back();
          return false;
        }
      };

      // Adjust the display based on the window size
      if (window.innerHeight < 80 || window.innerWidth < 80) {
        // Blank if window is too small
        document.body.style.display = 'none';
      };
      if (window.innerWidth < 200 || window.innerHeight < 150) {
        document.getElementById('back-link').style.display = 'none';
        document.getElementById('help-link').style.display = 'none';
      };
      if (window.innerWidth < 200) {
        document.getElementById('sorry').style.fontSize = '16px';
      };
      if (window.innerWidth < 150) {
        document.getElementById('promise').style.display = 'none';
      };
      if (window.innerHeight < 150) {
        document.getElementById('sorry').style.margin = '4px 0 0 0';
        document.getElementById('sorry').style.fontSize = '14px';
        document.getElementById('promise').style.display = 'none';
      };
    </script>
  </body>
</html>

ERR! Error in uploadAttachment Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
ERR! Error in uploadAttachment     at /Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/facebook-chat-api/utils.js:397:40
ERR! Error in uploadAttachment     at tryCatcher (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in uploadAttachment     at Function.Promise.attempt.Promise.try (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/method.js:31:24)
ERR! Error in uploadAttachment     at parseAndCheckLogin (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/facebook-chat-api/utils.js:395:22)
ERR! Error in uploadAttachment     at tryCatcher (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in uploadAttachment     at Promise._settlePromiseFromHandler (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in uploadAttachment     at Promise._settlePromiseAt (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in uploadAttachment     at Promise._settlePromises (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/promise.js:697:14)
ERR! Error in uploadAttachment     at Async._drainQueue (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in uploadAttachment     at Async._drainQueues (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in uploadAttachment     at Immediate.Async.drainQueues [as _onImmediate] (/Users/Josh/Dropbox/Programming/MarcusZuckerbot/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in uploadAttachment     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in uploadAttachment  [Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.]
```

**Comment by Schmavery** [comment]
@jobbogamer since I'm super smart and forgot to update npm last night, you might be helped by updating to master in the meantime.  A number of fixes have been made since 1.0.5.

**Comment by Schmavery** [comment]
@jobbogamer I just updated npm to 1.0.6.
Can you verify whether this has an effect on the issue you're experiencing?

**Comment by jobbogamer** [comment]
@Schmavery This is still happening in 1.0.6, same details and output as before.

**Comment by Schmavery** [comment]
Thanks for the update.

**Comment by bsansouci** [comment]
We're unable to reproduce this issue :/
<img width="594" alt="screen shot 2016-01-30 at 21 48 35" src="https://cloud.githubusercontent.com/assets/4534692/12700517/72dff982-c79b-11e5-8414-0d18db5e3465.png">
If you really want us to look into this, you can make an account and send the credentials to benjamin.sansouci@gmail.com.

**Comment by jobbogamer** [comment]
Don't worry about it, I've worked around the issue on my end (by using different images…). Thanks for looking into it :+1:

**Comment by Schmavery** [comment]
Thanks for letting us know :)
