### ISSUE TITLE
Not running in ubuntu but runs fine on windows

### ISSUE THREAD

**Issue by anaganisk** [Schmavery/facebook-chat-api#157]
When I run the script on windows its error free but when its run on an ubuntu server it gives the following error
/home/ubuntu/nodefbbot/node_modules/facebook-chat-api/utils.js:194
      ["p_" + userID]: 0
      ^
SyntaxError: Unexpected token [
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/nodefbbot/node_modules/facebook-chat-api/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by Schmavery** [comment]
Please update to the latest version of node.
