### ISSUE TITLE
Error on group chat message after awhile

### ISSUE THREAD

**Issue by bearbear12345** [Schmavery/facebook-chat-api#168]
```
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:469:22)
    at Promise._settlePromiseFromHandler (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:513:17)
    at Promise._settlePromiseAt (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (.../node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Hi.
After a period of time, group chat messages (Not sure if it affects all the groups, but it's affecting an important thread) raise the above error on reception.

The script is running on commit 443aaac49aca426a4031affeb14d481cedc6af47 (pretty sure) - I'm not sure if any of the recent commits have fixed this

**Comment by Schmavery** [comment]
Can you please update and try again? And include a minimal working example of this issue.  Thanks!

**Comment by Schmavery** [comment]
@bsansouci pretty hard to get anything out of this stack trace.  I guess it's possible we're not catching an exception somewhere.  I guess in `listen` given the context of when it happens.  @bearbear12345 am I correct in understanding that this happens when the api receives a message?

**Comment by bearbear12345** [comment]
@Schmavery I can't see how any part of my code would create this issue, so too am assuming that the error happens when the message is received.

**Comment by bearbear12345** [comment]
update: right now still no error, but i'll leave this issue open for ahwile longer

**Comment by bearbear12345** [comment]
Okay, I assume that the new version(s) have somehow solved this issue

Closing

**Comment by Schmavery** [comment]
Thanks for following up
