### ISSUE TITLE
Crash upon receiving the thumbs up sticker on Facebook

### ISSUE THREAD

**Issue by mrkno** [Schmavery/facebook-chat-api#173]
Origionally reported here: https://github.com/mrkno/Kassy/issues/78 by @ParasDPain
API Version: 1.0.2

I cannot reproduce on 1.0.2 or newer so I've asked that they test with a newer version of the API to see if the problem still exists.

**Origional Issue:**
The sticker in question is the mouse clicked/finger tapped thumbs up. It is not available in the sticker store but provided under messenger's attachment-bar.

When sent (of any size) Kassy crashes with the following log message
```
ERR! ERROR in listen -->  TypeError: Cannot read property 'caption' of undefined
ERR! ERROR in listen -->      at _formatAttachment (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:155:29)
ERR! ERROR in listen -->      at H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:250:12
ERR! ERROR in listen -->      at Array.map (native)
ERR! ERROR in listen -->      at formatAttachment (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:245:36)
ERR! ERROR in listen -->      at Object.formatMessage (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:267:18)
ERR! ERROR in listen -->      at parsePackets (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\src\listen.js:134:35)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\src\listen.js:86:12
ERR! ERROR in listen -->      at tryCatcher (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\async.js:15:14)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! ERROR in listen -->   [TypeError: Cannot read property 'caption' of undefined]
undefined
```
I would argue this to be an important issue because users tend to use that thumbs-up quite ofte

**Comment by mrkno** [comment]
It appears their issue was fixed by using a newer version of your API. Sorry for the noise :)

**Comment by bsansouci** [comment]
No problem! Glad we fixed it :)
