### ISSUE TITLE
login crash @ utils.js 

### ISSUE THREAD

**Issue by pilosof** [Schmavery/facebook-chat-api#180]
keeps crashing:

`/Users/pilo/Desktop/playgoround/fbmessgener/node_modules/facebook-chat-api/utils.js:194
      ["p_" + userID]: 0
      ^
SyntaxError: Unexpected token [
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/pilo/Desktop/playgoround/fbmessgener/node_modules/facebook-chat-api/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
Pilo-PRO:fbmessgener pilo$ node test.js `

**Comment by bsansouci** [comment]
You need to update nodejs. They recently added support for object literals with keys as variable.

**Comment by nmggithub** [comment]
I have the latest version of node and am still receiving this error.
