### ISSUE TITLE
Getting an error when trying to login

### ISSUE THREAD

**Issue by Mobilpadde** [Schmavery/facebook-chat-api#195]
I'm getting this error:

`
/home/node/node_modules/facebook-chat-api/utils.js:194
      ["p_" + userID]: 0
      ^
SyntaxError: Unexpected token [  
    at Module._compile (module.js:439:25)  
    at Object.Module._extensions..js (module.js:474:10)  
    at Module.load (module.js:356:32)  
    at Function.Module._load (module.js:312:12)  
    at Module.require (module.js:364:17)  
    at require (module.js:380:17)  
    at Object.<anonymous> (/home/node/node_modules/facebook-chat-api/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`

because of this [line](https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L194). Is that even legit code? Never seen something written in that way before.

Ps. I don't know how to format the code on github, sorry about that, so I've taken a picture of it, http://puu.sh/nC1NS/5fb0423981.png

**Comment by Schmavery** [comment]
Please check out the FAQs in the README and update node as recommended.

**Comment by Mobilpadde** [comment]
Oh, I'm sorry, completely overlooked that part...sorry!

**Comment by Schmavery** [comment]
No problem.  Btw, you can format code by surrounding it with a triple backticks [like this](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).  If you write 'js' after the first triple backtick, it will syntax highlight it with the assumption that it's javascript code.

**Comment by Mobilpadde** [comment]
Oh, thanks! :D
