### ISSUE TITLE
Sending audio files as an attachment

### ISSUE THREAD

**Issue by ICSandy** [Schmavery/facebook-chat-api#221]
I would like to send an audio file as an attachment. I attempted using api.sendMessage() to send the audio file attachment but I get an error. I can send attachments if it is a picture, but .wav or .mp3 files will not work and return this error:

```
ERR! Error in uploadAttachment TypeError: Cannot read property 'push' of undefined
ERR! Error in uploadAttachment     at /home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/src/sendMessage.js:208:50
ERR! Error in uploadAttachment     at Array.forEach (native)
ERR! Error in uploadAttachment     at /home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/src/sendMessage.js:202:15
ERR! Error in uploadAttachment     at /home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/src/sendMessage.js:46:9
ERR! Error in uploadAttachment     at tryCatcher (/home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in uploadAttachment     at Promise._settlePromiseFromHandler (/home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in uploadAttachment     at Promise._settlePromiseAt (/home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in uploadAttachment     at Promise._settlePromises (/home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! Error in uploadAttachment     at Async._drainQueue (/home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in uploadAttachment     at Async._drainQueues (/home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in uploadAttachment     at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/Desktop/botboy_test/test here/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in uploadAttachment     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in uploadAttachment  [TypeError: Cannot read property 'push' of undefined]

```

Here is the function I use that causes the error.
```
function speak(message) {
		var msg = {
			attachment: fs.createReadStream(__dirname + '/speech_plain.mp3')
		}
		api.sendMessage(msg, config.threadID);
}
```

I did some digging around in the sendMessage.js file to see if I could do anything with this. I found a list of different arrays that could handle different file type buffers (I think that's what it's doing anyway). Starting on line 188 of sendMessage.js

```
      form['message_batch[0][image_ids]'] = [];
      form['message_batch[0][gif_ids]'] = [];
      form['message_batch[0][file_ids]'] = [];
      form['message_batch[0][video_ids]'] = [];
```

I decided to add one more of just for kicks that looked like this
`form['message_batch[0][audio_ids]'] = [];`

I tried running my script after that and it actually kind of worked. What I mean by kind of is that it sent the file as a downloadable. Meaning other users cannot click on the audio file and listen to it directly within Facebook messenger.

This is what I wanted:
![audio-preview](https://cloud.githubusercontent.com/assets/5581387/14057750/c8ea2778-f2d7-11e5-9ce1-59c4f3a6d336.png)

And with my addition to the sendMessage.js file this is what I got after sending an audio file:
![downloadable-audio](https://cloud.githubusercontent.com/assets/5581387/14057753/d9f8ad1e-f2d7-11e5-86d2-e9b491cb775e.png)

It's close but I am looking for a way to send an audio attachment so users can preview it immediately instead of download and play. Does anyone have an idea on how I could get this to work the way I want?

**Comment by Schmavery** [comment]
I just played with this a little in the browser and it looks like audio_ids was right, but I guess we must be missing something else.  Have you tried with different formats?  Maybe only certain formats can play in messenger.  Attaching the browser request to look at later.

![image](https://cloud.githubusercontent.com/assets/2154522/14057981/c79cb21e-f2cd-11e5-86bb-cf12381eb854.png)

**Comment by ICSandy** [comment]
I've tried sending .mp3 and .wav normally through the browser and both formats work. The difference is when I drag and drop an audio file normally through the browser the other users can preview it. When I send it using my script it comes up as a downloadable attachment. So I'm thinking there needs to be some kind of headers set (maybe)? The way Facebook is interpreting the request is... what might be.. different? At this point I'm just guessing.

**Comment by GAMELASTER** [comment]
.mp4 is supported too as videos! :-)

**Comment by ErmanSayin** [comment]
I've tried fiddling with this too, yet had the same problems. Trying to upload MP4 files gives this error:

> ERR! Error in uploadAttachment { __ar: 1,
> ERR! Error in uploadAttachment   error: 1545012,
> ERR! Error in uploadAttachment   errorSummary: 'Temporary Failure',
> ERR! Error in uploadAttachment   errorDescription: 'There was a temporary error, please try again.',
> ERR! Error in uploadAttachment   transientError: 1,
> ERR! Error in uploadAttachment   payload: null,
> ERR! Error in uploadAttachment   bootloadable: {},
> ERR! Error in uploadAttachment   ixData: {},
> ERR! Error in uploadAttachment   lid: '6266299195519450143' }

**Comment by ErmanSayin** [comment]
MP4 videos seem to work, but would be nice to have audio only

**Comment by TexAgg** [comment]
I get the same error when sending .wav files:

```
ERR! Error in uploadAttachment TypeError: Cannot convert undefined or null to object
ERR! Error in uploadAttachment     at Function.keys (native)
ERR! Error in uploadAttachment     at C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\facebook-chat-api\src\sendMessage.js:203:28
ERR! Error in uploadAttachment     at Array.forEach (native)
ERR! Error in uploadAttachment     at C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\facebook-chat-api\src\sendMessage.js:202:15
ERR! Error in uploadAttachment     at C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\facebook-chat-api\src\sendMessage.js:46:9
ERR! Error in uploadAttachment     at tryCatcher (C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in uploadAttachment     at Promise._settlePromiseFromHandler (C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\bluebird\js\main\promise.js:507:31)
ERR! Error in uploadAttachment     at Promise._settlePromiseAt (C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\bluebird\js\main\promise.js:581:18)
ERR! Error in uploadAttachment     at Promise._settlePromises (C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\bluebird\js\main\promise.js:697:14)
ERR! Error in uploadAttachment     at Async._drainQueue (C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\bluebird\js\main\async.js:123:16)
ERR! Error in uploadAttachment     at Async._drainQueues (C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\bluebird\js\main\async.js:133:10)
ERR! Error in uploadAttachment     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\mgaik\Dropbox\Apps\Heroku\danksinatra\node_modules\bluebird\js\main\async.js:15:14)
ERR! Error in uploadAttachment     at tryOnImmediate (timers.js:534:15)
ERR! Error in uploadAttachment     at processImmediate [as _immediateCallback] (timers.js:514:5)
ERR! Error in uploadAttachment  [TypeError: Cannot convert undefined or null to object]
```

**Comment by GAMELASTER** [comment]
This failing because in [sendMessage.js](https://github.com/Schmavery/facebook-chat-api/blob/master/src/sendMessage.js#L191) it's missing an `audio_ids` array, but anyway, the message is not sent, maybe some POST variables missing on it. Im sending a compare of Messenger.com send audio request and request generated by sendMessage.js
```js
           original messenger.com request                                                     request made by facebook-chat-api
message_batch[0][action_type]:ma-type:user-generated-message                         'message_batch[0][action_type]': 'ma-type:user-generated-message',
message_batch[0][thread_id]:
message_batch[0][author]:fbid:100000203222282                                        'message_batch[0][author]': 'fbid:100000203222282',
message_batch[0][author_email]:
message_batch[0][timestamp]:1459546929814                                            'message_batch[0][timestamp]': 1459587518345,
message_batch[0][timestamp_absolute]:Dnes                                            'message_batch[0][timestamp_absolute]': 'Today',
message_batch[0][timestamp_relative]:23:42                                           'message_batch[0][timestamp_relative]': '10:58',
message_batch[0][timestamp_time_passed]:0                                            'message_batch[0][timestamp_time_passed]': '0',
message_batch[0][is_unread]:false                                                    'message_batch[0][is_unread]': false,
message_batch[0][is_forward]:false                                                   'message_batch[0][is_forward]': false,
message_batch[0][is_filtered_content]:false                                          'message_batch[0][is_filtered_content]': false,
message_batch[0][is_filtered_content_bh]:false                                       'message_batch[0][is_filtered_content_bh]': false,
message_batch[0][is_filtered_content_account]:false                                  'message_batch[0][is_filtered_content_account]': false,
message_batch[0][is_filtered_content_quasar]:false                                   'message_batch[0][is_filtered_content_quasar]': false,
message_batch[0][is_filtered_content_invalid_app]:false                              'message_batch[0][is_filtered_content_invalid_app]': false,
message_batch[0][is_spoof_warning]:false                                             'message_batch[0][is_spoof_warning]': false,
message_batch[0][source]:source:messenger:web                                        'message_batch[0][source]': 'source:chat:web',
message_batch[0][specific_to_list][0]:fbid:10000*****48239                           'message_batch[0][specific_to_list][0]': 'fbid:10000*****48239',
message_batch[0][specific_to_list][1]:fbid:100000203222282                           'message_batch[0][specific_to_list][1]': 'fbid:100000203222282',
message_batch[0][has_attachment]:true                                                'message_batch[0][has_attachment]': true,
message_batch[0][client_state]:send_to_server
message_batch[0][status]:7                                                           'message_batch[0][status]': '0',
message_batch[0][upload_id]:upload_1025
message_batch[0][offline_threading_id]:6121783525910314861                           'message_batch[0][offline_threading_id]': '6121953766541238776',
message_batch[0][message_id]:6121783525910314861                                     'message_batch[0][message_id]': '6121953766541238776',
message_batch[0][ephemeral_ttl_mode]:0                                               'message_batch[0][ephemeral_ttl_mode]:': '0',
message_batch[0][manual_retry_cnt]:0                                                 'message_batch[0][manual_retry_cnt]': '0',
message_batch[0][audio_ids][0]:1297411676942261                                      'message_batch[0][audio_ids]': [ 205291949861000 ],
message_batch[0][other_user_fbid]:10000*****48239                                    'message_batch[0][other_user_fbid]': 10000*****48239 }
client:mercury                                                                       client: 'mercury',
                                                                                     'message_batch[0][is_cleared]': false,
                                                                                     'message_batch[0][source_tags][0]': 'source:chat',
                                                                                     'message_batch[0][body]': 'Testing, ignore plz',
                                                                                     'message_batch[0][html_body]': false,
                                                                                     'message_batch[0][ui_push_phase]': 'V3',
                                                                                     'message_batch[0][threading_id]': '<blahblahblah@mail.projektitan.com>',
                                                                                     'message_batch[0][signatureID]': '1cc1191e',
                                                                                     'message_batch[0][image_ids]': [],
                                                                                     'message_batch[0][gif_ids]': [],
                                                                                     'message_batch[0][file_ids]': [],
                                                                                     'message_batch[0][video_ids]': [],
  
  
  
  
  
  
```

**Comment by Schmavery** [comment]
Looks like status is different and our package is missing client_state and maybe upload_id.  Someone could try adding those manually and see if they help.
