### ISSUE TITLE
Error when callback not provided in changeNickname

### ISSUE THREAD

**Issue by avikj** [Schmavery/facebook-chat-api#250]
I receive the following error when i do
```javascript
api.changeNickname('fbash', api.getCurrentUserID(), api.getCurrentUserID()); // error
```
However, when I pass in an empty callback as follows, it works.
```javascript
api.changeNickname('fbash', api.getCurrentUserID(), api.getCurrentUserID(), function(err){}); // no error
```

This is the error that I get. 
```shell
Unhandled rejection TypeError: callback is not a function
    at C:\Users\avik\Desktop\projects\fbash\node_modules\facebook-chat-api\src\changeNickname.js:33:16
    at tryCatcher (C:\Users\avik\Desktop\projects\fbash\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\avik\Desktop\projects\fbash\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\avik\Desktop\projects\fbash\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\avik\Desktop\projects\fbash\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\avik\Desktop\projects\fbash\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\avik\Desktop\projects\fbash\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\avik\Desktop\projects\fbash\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by bsansouci** [comment]
Good catch! Sorry about that, the callback's now optional.
