### ISSUE TITLE
getUserId Error

### ISSUE THREAD

**Issue by mjkaufer** [Schmavery/facebook-chat-api#26]
Hi,

Calling `api.getUserId` breaks the program. I tried calling the method itself manually and got an error, and calling `api.sendDirectMessage`, which uses `api.getUserId`, throws the same error.

The error is as follows

```
WARN Warning - sendDirectSticker and sendDirectMessage are deprecated. 
ERR! Error in getUserId TypeError: Cannot read property '0' of undefined
ERR! Error in getUserId     at /Users/matt/Projects/node_modules/facebook-chat-api/src/getUserId.js:21:25
ERR! Error in getUserId     at tryCatcher (/Users/matt/Projects/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:24:31)
ERR! Error in getUserId     at Promise._settlePromiseFromHandler (/Users/matt/Projects/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:454:31)
ERR! Error in getUserId     at Promise._settlePromiseAt (/Users/matt/Projects/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:530:18)
ERR! Error in getUserId     at Promise._settlePromises (/Users/matt/Projects/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:646:14)
ERR! Error in getUserId     at Async._drainQueue (/Users/matt/Projects/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:182:16)
ERR! Error in getUserId     at Async._drainQueues (/Users/matt/Projects/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:192:10)
ERR! Error in getUserId     at Immediate.Async.drainQueues [as _onImmediate] (/Users/matt/Projects/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in getUserId     at processImmediate [as _immediateCallback] (timers.js:367:17)
ERR! Error in getUserId  [TypeError: Cannot read property '0' of undefined]
[TypeError: Cannot read property '0' of undefined]

```

**Comment by mjkaufer** [comment]
See PR https://github.com/Schmavery/facebook-chat-api/pull/27
