### ISSUE TITLE
Errors after a few minutes of running

### ISSUE THREAD

**Issue by trgwii** [Schmavery/facebook-chat-api#266]
Using the latest version (1.1.0) with node v5.10.1 I'm getting the following errors after around 5-10 minutes of continuous listening:
```
ERR! ERROR in listen -->      at tryOnImmediate (timers.js:534:15)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:514:5)
ERR! ERROR in listen -->   [TypeError: Cannot read property 'length' of undefined]
[TypeError: Cannot read property 'length' of undefined]
ERR! ERROR in listen -->  TypeError: Cannot read property 'length' of undefined
ERR! ERROR in listen -->      at callback (C:\Users\TRG\Documents\node\fb\main.js:16:45)
ERR! ERROR in listen -->      at parsePackets (C:\Users\TRG\Documents\node\fb\node_modules\facebook-chat-api\src\listen.js:161:22)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at C:\Users\TRG\Documents\node\fb\node_modules\facebook-chat-api\src\listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (C:\Users\TRG\Documents\node\fb\node_modules\bluebird\js\main\util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (C:\Users\TRG\Documents\node\fb\node_modules\bluebird\js\main\promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (C:\Users\TRG\Documents\node\fb\node_modules\bluebird\js\main\promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (C:\Users\TRG\Documents\node\fb\node_modules\bluebird\js\main\promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (C:\Users\TRG\Documents\node\fb\node_modules\bluebird\js\main\async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (C:\Users\TRG\Documents\node\fb\node_modules\bluebird\js\main\async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\TRG\Documents\node\fb\node_modules\bluebird\js\main\async.js:15:14)
ERR! ERROR in listen -->      at tryOnImmediate (timers.js:534:15)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:514:5)
ERR! ERROR in listen -->   [TypeError: Cannot read property 'length' of undefined]
[TypeError: Cannot read property 'length' of undefined]
```

Have anyone had similar problems? Is this perhaps related to #265?

**Comment by GAMELASTER** [comment]
Can you write here an line 16 in main.js ?

**Comment by bsansouci** [comment]
This seems to come from your code `C:\Users\TRG\Documents\node\fb\main.js:16:45` Can you paste the code you wrote that causes this problem? Did you check the error before handling the response?

**Comment by trgwii** [comment]
Ah... line 16 is checking event.body.length.. I should probably check if event.body exists first?

**Comment by bsansouci** [comment]
Do you check the error that listen passes in as the first arg to the callback?

**Comment by trgwii** [comment]
Yes, here is part of my code:
```
	api.setOptions({ logLevel: 'warn', selfListen: true });
	api.listen(function callback (err, event) {
		if (err) return console.log(err);
		if (event.type === 'message' && event.body.length > 0 && event.threadID !== null) {
```

**Comment by bsansouci** [comment]
Can you add `console.log(m)` under [here](https://github.com/Schmavery/facebook-chat-api/blob/801b3f578a3b4802948a6ccf8b7f242c04292592/utils.js#L349) and paste the result when you receive a message (aka before the crash)

**Comment by trgwii** [comment]
Strange... I can't seem to reproduce the error today, anyway, I have added some extra checks for the existence of the body-property, and the console.log line in utils.js, I will update this issue if something gets logged.

**Comment by trgwii** [comment]
Got it, these are the results right before the error:
```
{ ofd_ts: 1461834382842,
  delta:
   { attachments: [ [Object] ],
     irisSeqId: '156761',
     messageMetadata:
      { actorFbId: '1640610814',
        messageId: 'mid.1461834382800:18dffcfa8526e04d72',
        offlineThreadingId: '6131377794254433952',
        tags: [Object],
        threadKey: [Object],
        timestamp: '1461834382812' },
     stickerId: '369239263222822',
     class: 'NewMessage' },
  type: 'delta',
  iseq: 156761,
  queue: 1640610814 }
```

**Comment by bsansouci** [comment]
OH attachement? Are you sending some attachement with no body?

**Comment by GAMELASTER** [comment]
Well, the last days the Messenger is really interesting, alot of bugs, messages dont sent etc.

**Comment by bsansouci** [comment]
@GAMELASTER What do you mean?

**Comment by trgwii** [comment]
@bsansouci nope, regular text message

**Comment by Schmavery** [comment]
Maybe you can json.stringify `m` so that we can see the whole thing.

**Comment by Schmavery** [comment]
Feel free to reopen
