### ISSUE TITLE
Timeout when uploading attachments

### ISSUE THREAD

**Issue by Destroyer** [Schmavery/facebook-chat-api#293]
Hi, I just started learning node today and I've created a simple app that takes my entire folder and uploads each file to facebook. It works fine with 1-3files that have 23MB each. But if I want to upload 5 or more I am getting 

```
ERR! Error in uploadAttachment Error: ETIMEDOUT
ERR! Error in uploadAttachment     at null._onTimeout (/nodeapp/node_modules/request/request.js:772:15)
ERR! Error in uploadAttachment     at Timer.listOnTimeout (timers.js:92:15)
ERR! Error in uploadAttachment  { [Error: ETIMEDOUT]
ERR! Error in uploadAttachment   cause: { [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false },
ERR! Error in uploadAttachment   isOperational: true,
ERR! Error in uploadAttachment   code: 'ETIMEDOUT',
ERR! Error in uploadAttachment   connect: false }
```

this is source:

```
var fs = require("fs"),
login = require("facebook-chat-api");

login({email: "mail", password: "pass"}, function callback (err, api) {
	if(err) return console.error(err);
	var yourID = 1;
	var folder = fs.readdirSync(__dirname + '/temp/');
	folder.forEach(function(value) {
	var msg = {
		body: value,
		attachment: fs.createReadStream(__dirname + '/temp/' + value)
	}
	api.sendMessage(msg, yourID);
	});
});
```

Am I doing something wrong? Or how can I fix that?

**Comment by Schmavery** [comment]
Hm.. it seems strange that sending more of the same kind of messages would cause it to fail.
Can you maybe try uploading them one at a time instead of all at once?
@bsansouci any ideas?

**Comment by Destroyer** [comment]
@Schmavery  what do you mean one at a time? This version sends 1 file per message

**Comment by Schmavery** [comment]
I mean wait until each message finishes uploading before sending the next one.

**Comment by Destroyer** [comment]
@Schmavery sorry for a stupid question but what's the correct approach with node? Can you show me?

```
var fs = require("fs"),
login = require("facebook-chat-api");

login({email: "mail", password: "pass"}, function callback (err, api) {
    if(err) return console.error(err);
    var yourID = 1;
    var folder = fs.readdirSync(__dirname + '/temp/');

    function uploader(i)
        {
                if (i < folder.length)
                {
                        var msg = {
                                body: folder[i],
                                attachment: fs.createReadStream(__dirname + '/temp/' + folder[i])
                        }
                        api.sendMessage(msg, yourID, function(err) {
                                if( err ){console.log('error: '+err);}
                                else {uploader(i+1);}
                        });
                }
        }
        uploader(0);

});
```

I tried this but it says 
```
ERR! Error in uploadAttachment { __ar: 1,
ERR! Error in uploadAttachment   error: 1468003,
ERR! Error in uploadAttachment   errorSummary: 'File Too Large',
ERR! Error in uploadAttachment   errorDescription: 'The file you uploaded is too large.',
ERR! Error in uploadAttachment   payload: null,
ERR! Error in uploadAttachment   bootloadable: {},
ERR! Error in uploadAttachment   ixData: {},
ERR! Error in uploadAttachment   lid: '6302005523380434885' }
```
Thanks

**Comment by Schmavery** [comment]
Great.  Might have also been a transient issue in facebook's system, but it's good to know for the future.  Feel free to reopen if this doesn't actually solve the issue.
