### ISSUE TITLE
Add support for facebook links

### ISSUE THREAD

**Issue by nguyenbrian** [Schmavery/facebook-chat-api#305]
Adding a URL for a Facebook event or a profile to my url field gives me this error.

`WARN parseAndCheckLogin: Got status code 500 retrying... 
ERR! ERROR in sendMessage -->  { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! ERROR in sendMessage -->    detail: [SyntaxError: Unexpected end of input],
ERR! ERROR in sendMessage -->    res: '' }`

I found that websites such as google.com or reddit.com work perfectly fine though. 

Is this happening because of the more detailed embed that Facebook uses for events? 
![Image](http://i.imgur.com/1hoV3wS.png)

**Comment by Schmavery** [comment]
If you send this as part of the message rather than setting it as a url, does it work?

**Comment by nguyenbrian** [comment]
It doesn't attach it to the bottom as seen in the picture and just shows up as text. 
![Pic](http://i.imgur.com/tAphTjj.png)

**Comment by Schmavery** [comment]
In that case, it sounds like facebook links are treated differently than regular ones, so this would be a feature request to support "facebook links".  It seems to me like a reasonable workaround for now will be including the facebook url as a regular message, even though it's not as pretty.

**Comment by nguyenbrian** [comment]
Sounds good! Thanks for the help!

**Comment by ianw11** [comment]
Is there any update on facebook links?
I'm also seeing an issue if a url is in the body and facebook includes its preview of the page, api.listen doesn't receive a callback.  However if you paste and send the message fast enough it works just fine

**Comment by Schmavery** [comment]
This is an issue specifically for links to pages on the facebook itself.  Are you seeing your second bug for all kinds of links? If so, can you open a new issue for it?  Doesn't sound like it's related to this, and is probably worth fixing.

**Comment by ianw11** [comment]
Thanks for the super quick reply, I created a new issue https://github.com/Schmavery/facebook-chat-api/issues/415

**Comment by Schmavery** [comment]
Is anyone able to check if this issue was fixed by #416 @notbrian

**Comment by luispena-minted** [comment]
@Schmavery i checked and this still failing, now we are getting:

`Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /Users/luispena/personal/facebook_test/node_modules/facebook-chat-api/utils.js:1040:15
    at tryCatcher (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/method.js:31:24)
    at /Users/luispena/personal/facebook_test/node_modules/facebook-chat-api/utils.js:987:24
    at tryCatcher (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/luispena/personal/facebook_test/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
`

Addind the facebook url as part of the message body works, but it doesnt append the thumbail and is not threated as a link.

**Comment by calvinbui** [comment]
Still happening on 1.5.1
