### ISSUE TITLE
Error when using api.sendMessage

### ISSUE THREAD

**Issue by Larry850806** [Schmavery/facebook-chat-api#317]
I try to login and send message, but I get error. There is no error until yesterday. This is my code:

```js
var login = require('facebook-chat-api');
login({'email': 'EMAIL', password: 'PASSWORD'}, function(err, api){
    api.sendMessage('Hello', '100001567752835', function(err){
        if(err) console.log(err);
    })
})
```

and error:

```
info Logging in...
info Logged in
info Request to reconnect
info Request to pull 1
info Request to pull 2
info Request to thread_sync
info Done logging in.

ERR! ERROR in sendMessage -->  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! ERROR in sendMessage -->      at /Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/utils.js:533:42
ERR! ERROR in sendMessage -->      at tryCatcher (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in sendMessage -->      at Function.Promise.attempt.Promise.try (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
ERR! ERROR in sendMessage -->      at /Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/utils.js:518:24
ERR! ERROR in sendMessage -->      at tryCatcher (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in sendMessage -->      at Promise._settlePromiseFromHandler (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! ERROR in sendMessage -->      at Promise._settlePromiseAt (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! ERROR in sendMessage -->      at Promise._settlePromises (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! ERROR in sendMessage -->      at Async._drainQueue (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in sendMessage -->      at Async._drainQueues (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in sendMessage -->      at Immediate.Async.drainQueues [as _onImmediate] (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in sendMessage -->      at tryOnImmediate (timers.js:543:15)
ERR! ERROR in sendMessage -->      at processImmediate [as _immediateCallback] (timers.js:523:5)
ERR! ERROR in sendMessage -->   Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! ERROR in sendMessage -->      at /Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/utils.js:533:42
ERR! ERROR in sendMessage -->      at tryCatcher (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in sendMessage -->      at Function.Promise.attempt.Promise.try (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
ERR! ERROR in sendMessage -->      at /Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/utils.js:518:24
ERR! ERROR in sendMessage -->      at tryCatcher (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in sendMessage -->      at Promise._settlePromiseFromHandler (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! ERROR in sendMessage -->      at Promise._settlePromiseAt (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! ERROR in sendMessage -->      at Promise._settlePromises (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! ERROR in sendMessage -->      at Async._drainQueue (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in sendMessage -->      at Async._drainQueues (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in sendMessage -->      at Immediate.Async.drainQueues [as _onImmediate] (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in sendMessage -->      at tryOnImmediate (timers.js:543:15)
ERR! ERROR in sendMessage -->      at processImmediate [as _immediateCallback] (timers.js:523:5)

Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/utils.js:533:42
    at tryCatcher (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
    at /Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/utils.js:518:24
    at tryCatcher (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/larry/Desktop/repos/FB-notification/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by ErmanSayin** [comment]
I get the same error, unfortunately.

**Comment by LINKIWI** [comment]
Looks like this is already tracked in #311

**Comment by Kurimizumi** [comment]
Please see issue #311 (as mentioned above) and pull requests #315 and #316.

You can manually patch it if you wish (if using 316), like this:
```
npm install git://github.com/Mini-Geek/facebook-chat-api.git#api-update
```
