### ISSUE TITLE
Error when trying to log in

### ISSUE THREAD

**Issue by p0358** [Schmavery/facebook-chat-api#333]
I'm getting this error when I try to log in:

```
ERR! Error in login: Error: read ECONNRESET
ERR! Error in login:   at exports._errnoException (util.js:1026:11)
ERR! Error in login:   at TLSWrap.onread (net.js:564:26)
ERR! Error in login:
ERR! Error in login:  { Error: read ECONNRESET
ERR! Error in login:   at exports._errnoException (util.js:1026:11)
ERR! Error in login:   at TLSWrap.onread (net.js:564:26)
ERR! Error in login:
ERR! Error in login:   cause:
ERR! Error in login:    { Error: read ECONNRESET
ERR! Error in login:      at exports._errnoException (util.js:1026:11)
ERR! Error in login:      at TLSWrap.onread (net.js:564:26)
ERR! Error in login:     code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
ERR! Error in login:   isOperational: true,
ERR! Error in login:   code: 'ECONNRESET',
ERR! Error in login:   errno: 'ECONNRESET',
ERR! Error in login:   syscall: 'read' }
```

Happens on 2 machines in different countries and I can normally log via browser. It still throws the same error as `Error in getThreadInfo` if it logs in, sometimes messages are being sent, sometimes they're not.

I got this now as well:
```
ERR! Error in getUserInfo  TypeError: Cannot read property 'name' of undefined
ERR! Error in getUserInfo   at callback (/var/www/Concierge/core/core_integrations/facebook.js:21:67)
ERR! Error in getUserInfo   at /var/www/Concierge/node_modules/facebook-chat-api/src/getUserInfo.js:49:14
ERR! Error in getUserInfo   at tryCatcher (/var/www/Concierge/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo   at Promise._settlePromiseFromHandler (/var/www/Concierge/node_modules/bluebird/js/main/promise.js:510:31)
ERR! Error in getUserInfo   at Promise._settlePromiseAt (/var/www/Concierge/node_modules/bluebird/js/main/promise.js:584:18)
ERR! Error in getUserInfo   at Async._drainQueue (/var/www/Concierge/node_modules/bluebird/js/main/async.js:128:12)
ERR! Error in getUserInfo   at Async._drainQueues (/var/www/Concierge/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in getUserInfo   at Immediate.Async.drainQueues (/var/www/Concierge/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in getUserInfo   at runCallback (timers.js:574:20)
ERR! Error in getUserInfo   at tryOnImmediate (timers.js:554:5)
ERR! Error in getUserInfo   at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by p0358** [comment]
OK, so at this point it lets me log in, but after sending one message, it throws the first error (`Error in getThreadInfo`) and won't send any other messages until I restart it. And it breaks after some time by itself anyways... Maybe it does break after it receives message? Can't be sure.

**Comment by Schmavery** [comment]
Looks like this is probably a real issue.. https://github.com/carpedm20/fbchat/issues/65
I can't tell initially what's causing this, someone will probably have to sniff the login process in the browser and attempt to see how it differs from what we're doing.

**Comment by p0358** [comment]
I started my bot yesterday and it works so far, maybe that was Facebook messing something up temporarily...

**Comment by Schmavery** [comment]
I didn't get this when trying it just now so hopefully facebook took care of this.  Thanks for reporting!
