### ISSUE TITLE
Can receive messages but can do anything else

### ISSUE THREAD

**Issue by miketamis** [Schmavery/facebook-chat-api#339]
currently get this error when I try to send replies

my code is the example provide (the echo bot)

My node version is v6.2.1

```
ERR! Error in getUserInfo { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! Error in getUserInfo   detail: 
ERR! Error in getUserInfo    SyntaxError: Unexpected token < in JSON at position 0
ERR! Error in getUserInfo        at Object.parse (native)
ERR! Error in getUserInfo        at /Users/miketamis/Development/Butters/node_modules/facebook-chat-api/utils.js:542:20
ERR! Error in getUserInfo        at tryCatcher (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo        at Function.Promise.attempt.Promise.try (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/method.js:31:24)
ERR! Error in getUserInfo        at /Users/miketamis/Development/Butters/node_modules/facebook-chat-api/utils.js:523:24
ERR! Error in getUserInfo        at tryCatcher (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo        at Promise._settlePromiseFromHandler (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/promise.js:510:31)
ERR! Error in getUserInfo        at Promise._settlePromiseAt (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/promise.js:584:18)
ERR! Error in getUserInfo        at Promise._settlePromises (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/promise.js:700:14)
ERR! Error in getUserInfo        at Async._drainQueue (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in getUserInfo        at Async._drainQueues (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in getUserInfo        at Immediate.Async.drainQueues [as _onImmediate] (/Users/miketamis/Development/Butters/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in getUserInfo        at tryOnImmediate (timers.js:543:15)
ERR! Error in getUserInfo        at processImmediate [as _immediateCallback] (timers.js:523:5),
ERR! Error in getUserInfo   res: '<html><head><title>Redirecting...</title><script>__DEV__=0;_script_path = "XChatUserInfoAsyncController";var uri_re=/^(?:(?:[^:\\/?#]+):)?(?:\\/\\/(?:[^\\/?#]*))?([^?#]*)(?:\\?([^#]*))?(?:#(.*))?/,target_domain=\'\';window.location.href.replace(uri_re,function(a,b,c,d){var e,f,g;e=f=b+(c?\'?\'+c:\'\');if(d){d=d.replace(/^(!|%21)/,\'\');g=d.charAt(0);if(g==\'/\'||g==\'\\\\\')e=d.replace(/^[\\\\\\/]+/,\'/\');}if(e!=f){if(window._script_path)document.cookie="rdir="+window._script_path+"; path=/; domain="+window.location.hostname.replace(/^.*(\\.facebook\\..*)$/i,\'$1\');window.location.replace(target_domain+e);}});</script><script type="text/javascript">/*<![CDATA[*/(function(){function si_cj(m){setTimeout(function(){new Image().src="https:\\/\\/error.facebook.com\\/common\\/scribe_endpoint.php?c=si_clickjacking&t=5327"+"&m="+m;},5000);}if(top!=self && !false){try{if(parent!=top){throw 1;}var si_cj_d=["apps.facebook.com","apps.beta.facebook.com"];var href=top.location.href.toLowerCase();for(var i=0;i<si_cj_d.length;i++){if (href.indexOf(si_cj_d[i])>=0){throw 1;}}si_cj("3 https:\\/\\/www.facebook.com\\/");}catch(e){si_cj("1 \\thttps:\\/\\/www.facebook.com\\/");window.document.write("\\u003Cstyle>body * {display:none !important;}\\u003C\\/style>\\u003Ca href=\\"#\\" onclick=\\"top.location.href=window.location.href\\" style=\\"display:block !important;padding:10px\\">Go to Facebook.com\\u003C\\/a>");/*LNOnqkgE*/}}}())/*]]>*/</script><script>window.location.replace("https:\\/\\/www.facebook.com\\/common\\/invalid_request.php?__req=6");</script><meta http-equiv="refresh" content="0;url=https://www.facebook.com/common/invalid_request.php?__req=6" /></head><body></body></html>' }
```

**Comment by Schmavery** [comment]
Are you still having this problem?

**Comment by jkp** [comment]
I've seen the same problem running my [autoresponder bot](https://github.com/jkp/fbautorespond).

**Comment by widder** [comment]
Same problem. Can receive messages but cannot send messages for several months now.

**Comment by Schmavery** [comment]
Thanks for letting us know, guys, we'll try and take a look at it in the morning. @bsansouci

**Comment by Schmavery** [comment]
I wonder if this is related https://github.com/carpedm20/fbchat/pull/77

**Comment by Schmavery** [comment]
Hey guys, @bsansouci was able to successfully run our tests.  Can someone share a short code sample that is failing so we can see if there's some issue?

**Comment by ivkos** [comment]
I'm hitting the same "unexpected token <" issue consistently when my bot has been logged in for an extended period of time (at least 2-3 days).

The workaround I'm currently doing is re-logging in. As far as I have tested, a full logout is not necessary, and you can reuse the appstate from the last session.

**Comment by Schmavery** [comment]
@ivkos this is #202 
Unexpected token < just means that facebook returned html instead of json and broke the parser (generally  due to a generic error).

**Comment by Schmavery** [comment]
Going to close this because it's probably #202??? Please comment/reopen if I'm wrong.

**Comment by jkp** [comment]
Seems the same.
