### ISSUE TITLE
Getting different errors when trying to use with hubot 

### ISSUE THREAD

**Issue by DavidAwad** [Schmavery/facebook-chat-api#414]
I've got a pretty specific problem and I'm not exactly sure how to solve it. 

I've been trying to use Hubot from within a docker container, using the [hubot-messenger](https://www.npmjs.com/package/hubot-messenger) adapter which uses facebook-chat-api underneath it. 

I've run into a variety of different problems when trying to run hubot using this plugin within heroku and from docker, when running on my local machine I've gotten different errors as well. 

So when running hubot using the chat api I can do something like the following:

### steps to reproduce. 
```shell
$ git clone http://github.com/github/hubot
Cloning into 'hubot'...
warning: redirecting to https://github.com/github/hubot/
remote: Counting objects: 8294, done.
remote: Total 8294 (delta 0), reused 0 (delta 0), pack-reused 8293
Receiving objects: 100% (8294/8294), 1.77 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (4672/4672), done.

$ cd hubot
$  npm install hubot-messenger
hubot@2.19.0 /Users/david/sandbox/hubot
└─┬ hubot-messenger@1.1.3
  ├─┬ facebook-chat-api@1.3.0
  │ ├── bluebird@2.11.0
. . . 
  │   └── uuid@3.0.1
  └── parent-require@1.0.0

$ ./bin/hubot -a messenger
Error: Cannot find module 'log'
  at Function.Module._resolveFilename (module.js:470:15)
  at Function.Module._load (module.js:418:25)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/david/sandbox/hubot/src/robot.coffee:2:18)
  at Object.<anonymous> (/Users/david/sandbox/hubot/src/robot.coffee:1:1)
  at Module._compile (module.js:571:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/david/sandbox/hubot/index.coffee:3:72)
  at Object.<anonymous> (/Users/david/sandbox/hubot/index.coffee:1:1)
  at Module._compile (module.js:571:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/david/sandbox/hubot/bin/hubot:4:11)
  at Object.<anonymous> (/Users/david/sandbox/hubot/bin/hubot:186:4)
  at Module._compile (module.js:571:32)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:425:7)
  at startup (bootstrap_node.js:146:9)
  at bootstrap_node.js:540:3
```

### Errors within container runtimes
When trying to run hubot from a working docker container, [container source](https://github.com/davidawad/doc-bot/) and [image](https://hub.docker.com/r/davidawad/doc-bot/) it seems to error out as well. 

docker errors:
```shell
docker logs 3e32334543584f53c5cf0c280cba2b3b8bb8da546951a740cd4c9d5a63b4d179
npm info it worked if it ends with ok
npm info using npm@2.13.3
npm info using node@v3.3.0
npm info preinstall bot@0.0.1
npm info package.json hubot-scripts@2.17.2 No license field.
npm info package.json hubot-slack@2.2.0 No license field.
npm info build /usr/src/app
npm info linkStuff bot@0.0.1
npm info install bot@0.0.1
npm info postinstall bot@0.0.1
npm info prepublish bot@0.0.1
npm info ok
[Tue Mar 07 2017 01:57:03 GMT+0000 (UTC)] ERROR Cannot load adapter messenger - SyntaxError: missing ) after argument list
``` 

heroku's errors are a little more useful:
```shell
$ heroku logs --tail
2017-03-07T02:08:20.000000+00:00 app[api]: Build started by user davidawad64@gmail.com
2017-03-07T02:08:45.259245+00:00 app[api]: Deploy 8a3837c by user davidawad64@gmail.com
2017-03-07T02:08:45.259245+00:00 app[api]: Release v14 created by user davidawad64@gmail.com
2017-03-07T02:08:45.461904+00:00 app[api]: Release v14 created by user davidawad64@gmail.com
2017-03-07T02:08:45.480564+00:00 heroku[web.1]: State changed from crashed to starting
2017-03-07T02:08:20.000000+00:00 app[api]: Build succeeded
2017-03-07T02:08:47.280877+00:00 heroku[web.1]: Starting process with command `bin/hubot -a messenger`
2017-03-07T02:08:54.206612+00:00 app[web.1]:
2017-03-07T02:08:54.206706+00:00 app[web.1]: /app/node_modules/hubot-messenger/node_modules/facebook-chat-api/utils.js:194
2017-03-07T02:08:54.206956+00:00 app[web.1]:       ["p_" + userID]: 0
2017-03-07T02:08:54.206958+00:00 app[web.1]:       ^
2017-03-07T02:08:54.209450+00:00 app[web.1]: [Tue Mar 07 2017 02:08:54 GMT+0000 (UTC)] ERROR Cannot load adapter messenger - SyntaxError: Unexpected token [
2017-03-07T02:08:54.309888+00:00 heroku[web.1]: State changed from starting to crashed
2017-03-07T02:08:54.311129+00:00 heroku[web.1]: State changed from crashed to starting
2017-03-07T02:08:54.285721+00:00 heroku[web.1]: Process exited with status 1
2017-03-07T02:08:56.175907+00:00 heroku[web.1]: Starting process with command `bin/hubot -a messenger`
2017-03-07T02:09:02.703857+00:00 heroku[web.1]: Process exited with status 1
2017-03-07T02:09:02.604470+00:00 app[web.1]:
2017-03-07T02:09:02.604567+00:00 app[web.1]: /app/node_modules/hubot-messenger/node_modules/facebook-chat-api/utils.js:194
2017-03-07T02:09:02.604817+00:00 app[web.1]:       ["p_" + userID]: 0
2017-03-07T02:09:02.604819+00:00 app[web.1]:       ^
2017-03-07T02:09:02.607133+00:00 app[web.1]: [Tue Mar 07 2017 02:09:02 GMT+0000 (UTC)] ERROR Cannot load adapter messenger - SyntaxError: Unexpected token [
2017-03-07T02:09:02.728452+00:00 heroku[web.1]: State ch
```

I haven't had the time to dig into this sub-sub-sub-module of my project, but I'm wondering if you've seen any of these errors before and have an idea of what might be going on. 

It seems like two different issues, one that comes up from the container runtimes and another from when being used within the context of my personal computer. 

Thanks!

**Comment by DavidAwad** [comment]
Now that you mention it, it looks like this package is using a much older release of fb-chat api. I'll try upgrading that to the latest version and maybe it will magically solve it :) 

I'll post an update here in a few days when I get a chance. Thanks for your help.

**Comment by Schmavery** [comment]
Regardless of the followup here, it's more likely there's a problem on the hubot adapter end, so I'm going to close this.  That said, if you run into any other problem with the api, please open another issue! 😄

**Comment by DavidAwad** [comment]
@Schmavery I figured it out. For anyone reading this in the future, I wrote out a dockerfile myself for hubot and had to do some extra npm installations in the dockerfile. I'll publish and open source more on this later.
