### ISSUE TITLE
Cannot read property 'getThreadHistory' of undefined

### ISSUE THREAD

**Issue by BilyanHadzhi** [Schmavery/facebook-chat-api#469]
I'm having trouble getting `getThreadHistory` to work.

I just started using the API and every function I tried seemed to be working properly.
I'm probably misusing the function somehow but I don't know how: I checked recent issues and tried copy-pasting the example from the [docs](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadHistory) but to no avail.

When I copy-paste the example code I don't get `'error: need callback'` but I still get `Cannot read property 'getThreadHistory' of undefined`

Here's my code: (I've looked up the thread ID in advance)
```js
const login = require('facebook-chat-api');

const credentials = {
  email: process.env.FB_EMAIL,
  password: process.env.FB_PASSWORD,
};

const threadId = /*some ID*/;
const timestamp = undefined;

login(credentials, (err, api) => {
  if (err) {
    console.error(err);
  }

  api.getThreadHistory(threadId, 5, timestamp, (err, history) => {
    if (err) {
      return console.error(err);
    }

    console.log(history);
  });
});
```

And here's the log: 
```
info login Logging in...
info login Logged in
info login Request to reconnect
info login Request to pull 1
info login Request to pull 2
info login Request to thread_sync
info login Done logging in.
ERR! login getThreadHistory: need callback
{ error: 'getThreadHistory: need callback' }
Unhandled rejection TypeError: Cannot read property 'getThreadHistory' of undefined
    at login (/home/billy/Coding/projects/z-class-chat-analysis/src/index.js:16:6)
    at /home/billy/Coding/projects/z-class-chat-analysis/node_modules/facebook-chat-api/index.js:420:7
    at tryCatcher (/home/billy/Coding/projects/z-class-chat-analysis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/billy/Coding/projects/z-class-chat-analysis/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/billy/Coding/projects/z-class-chat-analysis/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/billy/Coding/projects/z-class-chat-analysis/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/billy/Coding/projects/z-class-chat-analysis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/billy/Coding/projects/z-class-chat-analysis/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/billy/Coding/projects/z-class-chat-analysis/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by gamelaster** [comment]
@BilyanHadzhi do you use NPM version on Bleeding edge? Probably using NPM version but documentation from Bleeding edge.
Look this [documentation](https://github.com/Schmavery/facebook-chat-api/blob/f6464e8e3c576f99d001a1f3a71305787c28b261/DOCS.md#getThreadHistory) or use Bleeding edge (for now Bleeding edge is recommended)

**Comment by BilyanHadzhi** [comment]
@gamelaster Yup. That was it. Thank you!

Works after [switching to bleeding edge](https://github.com/Schmavery/facebook-chat-api#bleeding-edge).
