### ISSUE TITLE
Crash when someone was added or removed from the group chat

### ISSUE THREAD

**Issue by p0358** [Schmavery/facebook-chat-api#497]
That's what I get in console then:
```
ERR! listen TypeError: Cannot read property 'length' of undefined
ERR! listen     at /var/www/Concierge/modules/facebook/facebook.js:161:65
ERR! listen     at parsePackets (/var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:214:23)
ERR! listen     at Array.forEach (native)
ERR! listen     at /var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:109:12
ERR! listen     at tryCatcher (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:584:18)
ERR! listen     at Promise._settlePromises (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:700:14)
ERR! listen     at Async._drainQueue (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:123:16)
ERR! listen     at Async._drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:15:14)
ERR! listen     at runCallback (timers.js:672:20)
ERR! listen     at tryOnImmediate (timers.js:645:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:617:5)
ERR! listen
ERR! listen  { TypeError: Cannot read property 'length' of undefined
ERR! listen     at /var/www/Concierge/modules/facebook/facebook.js:161:65
ERR! listen     at parsePackets (/var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:214:23)
ERR! listen     at Array.forEach (native)
ERR! listen     at /var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:109:12
ERR! listen     at tryCatcher (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:584:18)
ERR! listen     at Promise._settlePromises (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:700:14)
ERR! listen     at Async._drainQueue (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:123:16)
ERR! listen     at Async._drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:15:14)
ERR! listen     at runCallback (timers.js:672:20)
ERR! listen     at tryOnImmediate (timers.js:645:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:617:5)
ERR! listen
ERR! listen   rawStackTrace:
ERR! listen    [ CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {} ] }
```

**Comment by Schmavery** [comment]
I scanned through the code path briefly and didn't see any .length that looked like the culprit (that's not to say they're not there).  Can you share the code that caused this to happen?

**Comment by bsansouci** [comment]
`ERR! listen     at /var/www/Concierge/modules/facebook/facebook.js:161:65` tells me this is in your code. What's the code around that line?

**Comment by p0358** [comment]
Sure, the code is from Concierge's facebook module here: https://github.com/concierge/facebook
```javascript
        fb({email: this.config.username, password: this.config.password}, (err, api) => {

            if (err) {

                LOG.error(err);

                throw new Error(err);

            }



            api.setOptions({

                listenEvents: true

            });



            this._integrationApi = new FacebookIntegrationApi(this.config.commandPrefix, api);

            this._stopListeningMethod = api.listen((err, event) => {

                if (err) {

                    this._stopListeningMethod();

                    throw new Error(err);

                }



                switch (event.type) {

                    case 'message':

                    {

                        this._getSenderName(api, event, name => {

                            const data = shim.createEvent(event.threadID, event.senderID, name, event.body + '');

                            callback(this._integrationApi, data);

                        });

                        break;

                    }

                    case 'event':

                        switch (event.logMessageType) {

                            case 'log:unsubscribe':

                            {

                                const usrs = event.logMessageData.removed_participants,

                                    threadInfo = this._integrationApi.getUsers();

                                for (let i = 0; i < usrs.length; i++) {

                                    usrs[i] = usrs[i].split(':')[1];

                                    if (threadInfo[event.threadID] && threadInfo[event.threadID][usrs[i]]) {

                                        delete threadInfo[event.threadID][usrs[i]];

                                    }

                                }

                                break;

                            }

                            case 'log:subscribe':

                            {

                                const usrs = event.logMessageData.added_participants;

                                for (let i = 0; i < usrs.length; i++) {

                                    usrs[i] = usrs[i].split(':')[1];

                                }

                                this._getSenderInfo(usrs, api, event, () => {});

                                break;

                            }

                            default:

                                LOG.silly(`Event '${event.logMessageType}' was unhandled.`);

                                break;

                        }

                        break;

                    case 'read_receipt':

                    {

                        this.emit('read', {

                            sender_id: event.reader,

                            thread_id: event.threadID

                        });

                        break;

                    }

                    default:

                        LOG.silly(`Message '${event.type}' was unhandled.`);

                        break;

                }

            });

        });
```
This is the particular code fragment:
```javascript
                            case 'log:subscribe':

                            {

                                const usrs = event.logMessageData.added_participants;

                                for (let i = 0; i < usrs.length; i++) {

                                    usrs[i] = usrs[i].split(':')[1];

                                }

                                this._getSenderInfo(usrs, api, event, () => {});

                                break;

                            }
```
And the issue I created there: https://github.com/concierge/facebook/issues/2

**Comment by Schmavery** [comment]
Thanks for sharing this.  It looks like the signature of logMessageData was changed without being documented a while ago: https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L485

Unfortunately the docs for this area (`listen`) aren't very good, there's an issue open to solve this which I'd love to help someone with if they want to give it a shot: https://github.com/Schmavery/facebook-chat-api/issues/463

Can you try updating the name and see if it fixes the problem?

**Comment by mrkno** [comment]
The original code has been updated to use the new API and has a try-catch now to prevent errors being thrown further up. @p0358 please test the changes (`/kpm update facebook` should be sufficient to pull them in).
I might take a look at #463 later today if I have time.

**Comment by Schmavery** [comment]
Thanks for fixing!  @p0358 let us know if it doesn't work :)
