### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by p0358** [Schmavery/facebook-chat-api#529]
That's what I keep getting in less than a day from logging in:
```
ERR! listen URIError: URI malformed
ERR! listen     at decodeURIComponent (native)
ERR! listen     at parsePackets (/var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:185:35)
ERR! listen     at Array.forEach (native)
ERR! listen     at /var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:109:12
ERR! listen     at tryCatcher (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:584:18)
ERR! listen     at Promise._settlePromises (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:700:14)
ERR! listen     at Async._drainQueue (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:123:16)
ERR! listen     at Async._drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:15:14)
ERR! listen     at runCallback (timers.js:672:20)
ERR! listen     at tryOnImmediate (timers.js:645:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:617:5)
ERR! listen
ERR! listen  { URIError: URI malformed
ERR! listen     at decodeURIComponent (native)
ERR! listen     at parsePackets (/var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:185:35)
ERR! listen     at Array.forEach (native)
ERR! listen     at /var/www/Concierge/modules/facebook/node_modules/facebook-chat-api/src/listen.js:109:12
ERR! listen     at tryCatcher (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:584:18)
ERR! listen     at Promise._settlePromises (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/promise.js:700:14)
ERR! listen     at Async._drainQueue (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:123:16)
ERR! listen     at Async._drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (/var/www/Concierge/modules/facebook/node_modules/bluebird/js/main/async.js:15:14)
ERR! listen     at runCallback (timers.js:672:20)
ERR! listen     at tryOnImmediate (timers.js:645:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:617:5)
ERR! listen
ERR! listen   rawStackTrace:
ERR! listen    [ CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {},
ERR! listen      CallSite {} ] }
```

**Comment by Schmavery** [comment]
What version of the api are you using (npm version/github master etc)? This looks very similar to issue #516, which was recently fixed in master.
If you can confirm that updating to master fixes the issue, I'd be happy to cut a new release with the fix 😄

**Comment by scitbiz** [comment]
I have the same problem!
npm: 5.3.0
node: 8.5.0
github master, ver: 1.4.0

**Comment by Schmavery** [comment]
@scitbiz are you saying that updating to the tip of master *isn't* fixing your problem?

**Comment by knyzorg** [comment]
I confirm that master does not have this issue any longer.

**Comment by Schmavery** [comment]
Thanks @knyzorg
