### ISSUE TITLE
Receiving unknown attachments results in console getting spammed with the same error

### ISSUE THREAD

**Issue by ivkos** [Schmavery/facebook-chat-api#551]
When the API receives an attachment of an unknown type, it starts infinitely spamming the console with the same error. There are some recursive calls in `listen()`. Could it be related to them?

```
ERR! listen Error: unrecognized attach_file of type MessageAudio`{
ERR! listen     "blob_attachment": {
ERR! listen         "__typename": "MessageAudio",
ERR! listen         "attribution_app": null,
ERR! listen         "attribution_metadata": null,
ERR! listen         "filename": "audioclip-1509700639000-3947.mp4",
ERR! listen         "playable_url": "[...]",
ERR! listen         "playable_duration_in_ms": 3947,
ERR! listen         "is_voicemail": false,
ERR! listen         "audio_type": "VOICE_MESSAGE",
ERR! listen         "url_shimhash": "[...]",
ERR! listen         "url_skipshim": true
ERR! listen     }
ERR! listen } attachment2: {
ERR! listen     "id": "",
ERR! listen     "image_data": {}
ERR! listen }`
ERR! listen     at _formatAttachment (facebook-chat-api\utils.js:446:13)
ERR! listen     at attachments.map.v (facebook-chat-api\utils.js:478:55)
ERR! listen     at Array.map (<anonymous>)
ERR! listen     at Object.formatDeltaMessage (facebook-chat-api\utils.js:478:46)
ERR! listen     at resolveAttachmentUrl (facebook-chat-api\src\listen.js:159:40)
ERR! listen     at resolveAttachmentUrl (facebook-chat-api\src\listen.js:168:30)
ERR! listen     at parsePackets (facebook-chat-api\src\listen.js:171:19)
ERR! listen     at Array.forEach (<anonymous>)
ERR! listen     at facebook-chat-api\src\listen.js:109:12
ERR! listen     at tryCatcher (facebook-chat-api\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (facebook-chat-api\node_modules\bluebird\js\main\promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (facebook-chat-api\node_modules\bluebird\js\main\promise.js:584:18)
ERR! listen     at Promise._settlePromises (facebook-chat-api\node_modules\bluebird\js\main\promise.js:700:14)
ERR! listen     at Async._drainQueue (facebook-chat-api\node_modules\bluebird\js\main\async.js:123:16)
ERR! listen     at Async._drainQueues (facebook-chat-api\node_modules\bluebird\js\main\async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (facebook-chat-api\node_modules\bluebird\js\main\async.js:15:14)
```

**Comment by Bjornskjald** [comment]
Can confirm, it bothers me for 3 hours now

**Comment by Schmavery** [comment]
Hey @mitchcapper, looks like we found some more attachment types.

@ivkos @Bjornskjald please include the json blobs for all the different types of errors you find to help with implementing formatting functions for them! Thanks 😄

**Comment by mitchcapper** [comment]
Thanks @ivkos can you provide a similar output for video and I will fix both?

**Comment by Schmavery** [comment]
@ivkos sorry, just saw your PR, looking now!

**Comment by mitchcapper** [comment]
even better a PR for both:)

**Comment by reportrushib1** [comment]
looks like facebook has changed the structure of the respone. they have removed the attach_type key from the response, instead created attachments with key as {attach_type}_attachment and this key has all the values(properties) inside it. I have modified the code to work for stickers and If you would like me to put a pr for it I would gladly do it. Would loved to change the rest of them if its not for my exams.

sample response
`{ sticker_attachment: 
   { id: '369239263222822',
     pack: { id: '227877430692340' },
     label: 'Like, thumbs up',
     frame_count: 1,
     frame_rate: 83,
     frames_per_row: 1,
     frames_per_column: 1,
     sprite_image_2x: null,
     sprite_image: null,
     padded_sprite_image: null,
     padded_sprite_image_2x: null,
     url: 'https://scontent.xx.fbcdn.net/v/t39.1997-6/851557_369239266556155_759568595_n.png?_nc_ad=z-m&_nc_cid=0&oh=8bfd127ce3a4ae8c53f87b0e29eb6de5&oe=5A761DDC',
     height: 70,
     width: 70 } }
`

sorry if my english is poor.

**Comment by Bjornskjald** [comment]
```
{"blob_attachment":{"__typename":"MessageIma
ge","attribution_app":null,"attribution_metadata":null,"filename":"image-(some numbers)","preview":{"uri":"(very complicated url)","height":77,"width":98},"large_preview":{"uri":
"(one more long url)",
"height":77,"width":98},"thumbnail":{"uri":"(also here)"},"photo_encodings":[],"legac
y_attachment_id":"(more numbers)","original_dimensions":{"x":98,"y":77},"ori
ginal_extension":"png","render_as_sticker":false}}
```

**Comment by Bjornskjald** [comment]
Sticker: 
```json
{
    "sticker_attachment":{
        "id":"126361967548600",
        "pack":{
            "id":"126361870881943"
        },
        "label":"Laughing face",
        "frame_count":0,
        "frame_rate":83,
        "frames_per_row":0,
        "frames_per_column":0,
        "sprite_image_2x":null,
        "sprite_image":null,
        "padded_sprite_image":null,
        "padded_sprite_image_2x":null,
        "url":"https://scontent.xx.fbcdn.net/v/t39.1997-6/851575_126361970881933_2050936102_n.png?_nc_ad=z-m&_nc_cid=0&oh=4089bb1981579b774bc67b3a231ea326&oe=5A71F896",
        "height":600,
        "width":600
    }
}
```

**Comment by Bjornskjald** [comment]
Like (default emoji):
```json
{
    "sticker_attachment":{
        "id":"369239263222822",
        "pack":{
            "id":"227877430692340"
        },
        "label":"Like, thumbs up",
        "frame_count":1,
        "frame_rate":83,
        "frames_per_row":1,
        "frames_per_column":1,
        "sprite_image_2x":null,
        "sprite_image":null,
        "padded_sprite_image":null,
        "padded_sprite_image_2x":null,
        "url":"https://scontent.xx.fbcdn.net/v/t39.1997-6/851557_369239266556155_759568595_n.png?_nc_ad=z-m&_nc_cid=0&oh=8bfd127ce3a4ae8c53f87b0e29eb6de5&oe=5A761DDC",
        "height":70,
        "width":70
    }
}
```

**Comment by mitchcapper** [comment]
@Bjornskjald 5a60046 fixed those if you use master those should work I believe.

**Comment by Bjornskjald** [comment]
Oh wow, really?
I'm gonna try it out, btw why isn't it on NPM if the latest version is crashing on every attachment?

**Comment by mitchcapper** [comment]
it was just committed a few days ago:) We are still working to update all the formats.

**Comment by Bjornskjald** [comment]
Github version works perfectly, thanks!
I'm hoping NPM version gets updated soon

**Comment by ivkos** [comment]
I think this bug generally happens when [_formatAttachment](https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L231) throws an error. I also think it causes the api to stop listening. Last night, I saw that my bot had stopped responding due to a TypeError thrown in ` _formatAttachment` caused by accessing a property of undefined/null (#553).

**Comment by Schmavery** [comment]
will close this in favor of #553
