### ISSUE TITLE
Can't parse message object for messages sent with Tenor GIF Keyboard Bot

### ISSUE THREAD

**Issue by Limvot** [Schmavery/facebook-chat-api#564]
I was working on getting the matrix-puppet-facebook bridge to support more than just text again when I ran across this crash. Here's the stack trace:

> matrix-puppet:facebook:client error undefined { error: 'Problem parsing message object. Please open an issue at https://github.com/Schmavery/facebook-chat-api/issues.',
  detail:
   TypeError: Cannot read property 'text' of null
       at _formatAttachment (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/utils.js:445:55)
       at attachments.map.v (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/utils.js:502:55)
       at Array.map (native)
       at Object.formatDeltaMessage (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/utils.js:502:46)
       at resolveAttachmentUrl (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/src/listen.js:214:38)
       at resolveAttachmentUrl (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/src/listen.js:231:30)
       at parsePackets (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/src/listen.js:234:19)
       at Array.forEach (native)
       at /home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/src/listen.js:133:12
       at tryCatcher (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
       at Promise._settlePromiseFromHandler (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
       at Promise._settlePromiseAt (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
       at Promise._settlePromises (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
       at Async._drainQueue (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
       at Async._drainQueues (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
       at Immediate.Async.drainQueues (/home/nathan/matrix-puppet-facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5),
  res:
   { ofd_ts: 1513218943276,
     delta:
      { attachments: [Object],
        genericDataMap: [Object],
        irisSeqId: '100611',
        messageMetadata: [Object],
        class: 'NewMessage' },
     type: 'delta',
     iseq: 100611,
     queue: 100004048574687 },
  type: 'parse_error' }

**Comment by Schmavery** [comment]
@Limvot sorry this one slipped through the cracks. I'd imagine it's fixed right now but if it's not feel free to let us know and we'll open it right back up.
