### ISSUE TITLE
Problem parsing message object

### ISSUE THREAD

**Issue by inoriyuzuriha2018** [Schmavery/facebook-chat-api#587]
When I got the facebook link attached to the image it stopped the program
```
{ error: 'Problem parsing message object. Please open an issue at https://github.com/Schmavery/facebook-chat-api/issues.',
  detail: TypeError: Cannot read property 'text' of null
    at _formatAttachment (E:\bot\node_modules\facebook-chat-api\utils.js:453:46)
    at attachments.map.v (E:\bot\node_modules\facebook-chat-api\utils.js:502:55)
    at Array.map (<anonymous>)
```

**Comment by ravkr** [comment]
@inoriyuzuriha2018 does everything work well now?

**Comment by Schmavery** [comment]
@inoriyuzuriha2018 we published a new version to npm that should handle attachments better so feel free to give it a try and reopen if it doesn't work.
