### ISSUE TITLE
api.logout() fails with a TypeError

### ISSUE THREAD

**Issue by ivkos** [Schmavery/facebook-chat-api#590]
```
TypeError: Cannot read property 'instances' of undefined
    at /app/node_modules/facebook-chat-api/src/logout.js:18:35
    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by Schmavery** [comment]
Haha this looks a little suspicious:
https://github.com/Schmavery/facebook-chat-api/blob/bd8ee310c584d0d620b4e3d1567b6de952b6ebf3/src/logout.js#L18-L20
Can you print out the value of `resData` or `resData.jsmods` and post it here (after stripping out any sensitive info) to see what we need to change?
Unfortunately logout is a little flaky because we classically have had to parse html to get the relevant values. Another thing to try is to observe the network calls when logging out in a browser to see if they've replaced it with a nicer request.
