### ISSUE TITLE
Some error.

### ISSUE THREAD

**Issue by lequanglam** [Schmavery/facebook-chat-api#593]
```
ERR! listen  Error: unrecognized attach_file `{"blob_attachment":{"__typename":"MessageImage","attribution_app":null,"attribution_metadata":null,"filename":"image-381098775696635","preview":{"uri":"https://scontent-mxp1-1.xx.fbcdn.net/v/t34.00/p280x280/28511514_381098775696635_1945988029_n.png?_nc_ad=zm&_nc_cid=0&oh=df51b699099cd239b2671b4e1f50b6d6&oe=5A98EA1F","height":280,"width":474},"large_preview":{"uri":"https://scontent-mxp1-1.xx.fbcdn.net/v/t35.00/p480x480/28555046_381098775696635_1945988029_o.png?_nc_ad=zm&_nc_cid=0&oh=141ee201fc18505b10b282052219def0&oe=5A98F60A","height":480,"width":811},"thumbnail":{"uri":"https://scontent-mxp1-1.xx.fbcdn.net/v/t34.00/s64x64/28511514_381098775696635_1945988029_n.png?_nc_ad=z-m&_nc_cid=0&oh=2581170c9c26611f3b0a80087e27be91&oe=5A98C9EA"},"photo_encodings":[],"legacy_attachment_id":"381098775696635","original_dimensions":{"x":1679,"y":993},"original_extension":"png","render_as_sticker":false}}`
ERR! listen     at _formatAttachment (E:\chatbot\node_modules\facebook-chat-api\utils.js:354:13)
ERR! listen     at attachments.map.v (E:\chatbot\node_modules\facebook-chat-api\utils.js:376:55)
ERR! listen     at Array.map (<anonymous>)
ERR! listen     at Object.formatDeltaMessage (E:\chatbot\node_modules\facebook-chat-api\utils.js:376:46)
ERR! listen     at resolveAttachmentUrl (E:\chatbot\node_modules\facebook-chat-api\src\listen.js:159:40)
ERR! listen     at resolveAttachmentUrl (E:\chatbot\node_modules\facebook-chat-api\src\listen.js:168:30)
ERR! listen     at parsePackets (E:\chatbot\node_modules\facebook-chat-api\src\listen.js:171:19)
ERR! listen     at Array.forEach (<anonymous>)
ERR! listen     at E:\chatbot\node_modules\facebook-chat-api\src\listen.js:109:12
ERR! listen     at tryCatcher (E:\chatbot\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (E:\chatbot\node_modules\bluebird\js\main\promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (E:\chatbot\node_modules\bluebird\js\main\promise.js:584:18)
ERR! listen     at Promise._settlePromises (E:\chatbot\node_modules\bluebird\js\main\promise.js:700:14)
ERR! listen     at Async._drainQueue (E:\chatbot\node_modules\bluebird\js\main\async.js:123:16)
ERR! listen     at Async._drainQueues (E:\chatbot\node_modules\bluebird\js\main\async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (E:\chatbot\node_modules\bluebird\js\main\async.js:15:14)
```
I received this when someone is sending me a image. Fix it, please!

**Comment by ravkr** [comment]
are you using npm or bleeding edge?

**Comment by lequanglam** [comment]
@ravkr npm.

**Comment by ravkr** [comment]
Do you get the same error with bleeding edge version?

**Comment by lequanglam** [comment]
@ravkr yep?

**Comment by ravkr** [comment]
Are you sure? How did you install it?

**Comment by ravkr** [comment]
do you still have the problem or can we close this issue?

**Comment by lequanglam** [comment]
just close thread. problem solved.

**Comment by Schmavery** [comment]
Thanks for helping ravkr :)
