### ISSUE TITLE
Bailing out 400 Error

### ISSUE THREAD

**Issue by adminy** [Schmavery/facebook-chat-api#600]
`Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
    at /proj/node_modules/facebook-chat-api/utils.js:667:42
    at tryCatcher (/proj/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/proj/node_modules/bluebird/js/main/method.js:31:24)
    at /proj/node_modules/facebook-chat-api/utils.js:637:24
    at tryCatcher (/proj/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/proj/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/proj/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/proj/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/proj/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/proj/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)`

It just happens from time to time, I have to restart the server to fix the problem.

**Comment by Bjornskjald** [comment]
The only valuable thing you got there is `status code: 400`. Could you try to debug it yourself? (add a `console.log` in some places where it crashes)

**Comment by Schmavery** [comment]
@adminy I think what @Bjornskjald is saying is that we don't know either, and would be interested in any insights you gain by poking around at this error. If it's intermittent and seems random, might be some network issue we need to handle better somehow.

**Comment by adminy** [comment]
@Schmavery it happens very infrequent indeed. Sorry I wouldn’t know why it occured either.

**Comment by bsansouci** [comment]
I think the only way we could fix this would be to figure out which request causes the "bad request 400".
