### ISSUE TITLE
Error when setting an event

### ISSUE THREAD

**Issue by Bjornskjald** [Schmavery/facebook-chat-api#607]
```javascript
{ error: 'Problem parsing message object. Please open an issue at https://github.com/Schmavery/facebook-chat-api/issues.',
  detail: TypeError: Cannot read property 'text' of null
    at _formatAttachment (/path/node_modules/facebook-chat-api/utils.js:453:46)
    at attachments.map.v (/path/node_modules/facebook-chat-api/utils.js:502:55)
    at Array.map (<anonymous>)
    at Object.formatDeltaMessage (/path/node_modules/facebook-chat-api/utils.js:502:46)
    at resolveAttachmentUrl (/path/node_modules/facebook-chat-api/src/listen.js:214:38)
    at resolveAttachmentUrl (/path/node_modules/facebook-chat-api/src/listen.js:231:30)
    at parsePackets (/path/node_modules/facebook-chat-api/src/listen.js:234:19)
    at Array.forEach (<anonymous>)
    at /path/node_modules/facebook-chat-api/src/listen.js:133:12
    at tryCatcher (/path/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/path/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/path/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/path/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/path/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/path/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/path/node_modules/bluebird/js/main/async.js:15:14),
  res:
   { ofd_ts: 1520765122540,
     delta:
      { attachments: [Array],
        irisSeqId: '7233',
        messageMetadata: [Object],
        class: 'NewMessage' },
     type: 'delta',
     iseq: 7233,
     queue: 100018572888779 },
  type: 'parse_error' }
```

**Comment by ravkr** [comment]
could we see the code?

**Comment by Bjornskjald** [comment]
Of course.

![code](https://user-images.githubusercontent.com/26630168/37289862-0f7aa6c8-260b-11e8-91f2-a10683058f2a.png)

**Comment by Bjornskjald** [comment]
Might be related to #587.

**Comment by ravkr** [comment]
I'll try to fix it in a moment

**Comment by ravkr** [comment]
can you give me an example of message that crashes it?

**Comment by Bjornskjald** [comment]
Any plan creation crashes it.

**Comment by ravkr** [comment]
thank you, gimme a moment...
