### ISSUE TITLE
parseAndCheckLogin JSON.parse error

### ISSUE THREAD

**Issue by ravkr** [Schmavery/facebook-chat-api#616]
While testing my new function I've found that Facebook returns two JSON objects in one response. In this case JSON.parse throws an error, what shall we do to make it work?

```
verb parseAndCheckLogin {"o0":{"errors":[{"message":"Invalid values provided for variables of operation \"MessengerThreadlist\": Value \"Array { 0 => \"blocked\" }\" cannot be used for variable \"$tags\": List item #0 has incompatible type with this list: There is no value named \"blocked\" in the enum \"MessagingGraphQLTags\".","severity":"CRITICAL","code":1675012,"api_error_code":null,"summary":"Brak mo\u017cliwo\u015bci rozpatrzenia pro\u015bby","description":"Wyst\u0105pi\u0142 problem w zrealizowaniu Twojego \u017c\u0105dania. Pracujemy nad jak najszybszym rozwi\u0105zaniem.","is_silent":false,"is_transient":false,"requires_reauth":false,"allow_user_retry":false,"debug_info":"Invalid values provided for variables of operation \"MessengerThreadlist\": Value \"Array { 0 => \"blocked\" }\" cannot be used for variable \"$tags\": List item #0 has incompatible type with this list: There is no value named \"blocked\" in the enum \"MessagingGraphQLTags\".","query_path":null,"fbtrace_id":"B35QJcgcuU1"}]}}
verb parseAndCheckLogin                               {
verb parseAndCheckLogin    "successful_results": 0,
verb parseAndCheckLogin    "error_results": 1,
verb parseAndCheckLogin    "skipped_results": 0
verb parseAndCheckLogin }
ERR! getThreadListGraphQL { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! getThreadListGraphQL   detail: SyntaxError: Unexpected token { in JSON at position 1024
ERR! getThreadListGraphQL     at JSON.parse (<anonymous>)
ERR! getThreadListGraphQL     at C:\Dane\node\update\facebook-chat-api\utils.js:847:20
ERR! getThreadListGraphQL     at tryCatcher (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\util.js:26:23)
ERR! getThreadListGraphQL     at Function.Promise.attempt.Promise.try (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\method.js:31:24)
ERR! getThreadListGraphQL     at C:\Dane\node\update\facebook-chat-api\utils.js:813:24
ERR! getThreadListGraphQL     at tryCatcher (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\util.js:26:23)
ERR! getThreadListGraphQL     at Promise._settlePromiseFromHandler (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\promise.js:510:31)
ERR! getThreadListGraphQL     at Promise._settlePromiseAt (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\promise.js:584:18)
ERR! getThreadListGraphQL     at Promise._settlePromises (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\promise.js:700:14)
ERR! getThreadListGraphQL     at Async._drainQueue (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\async.js:123:16)
ERR! getThreadListGraphQL     at Async._drainQueues (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\async.js:133:10)
ERR! getThreadListGraphQL     at Immediate.Async.drainQueues [as _onImmediate] (C:\Dane\node\update\facebook-chat-api\node_modules\bluebird\js\main\async.js:15:14)
ERR! getThreadListGraphQL     at runCallback (timers.js:800:20)
ERR! getThreadListGraphQL     at tryOnImmediate (timers.js:762:5)
ERR! getThreadListGraphQL     at processImmediate [as _immediateCallback] (timers.js:733:5),
ERR! getThreadListGraphQL   res: '{"o0":{"errors":[{"message":"Invalid values provided for variables of operation \\"MessengerThreadlist\\": Value \\"Array { 0 => \\"blocked\\" }\\" cannot be used for variable \\"$tags\\": List item #0 has incompatible type with this list: There is no value named \\"blocked\\" in the enum \\"MessagingGraphQLTags\\".","severity":"CRITICAL","code":1675012,"api_error_code":null,"summary":"Brak mo\\u017cliwo\\u015bci rozpatrzenia pro\\u015bby","description":"Wyst\\u0105pi\\u0142 problem w zrealizowaniu Twojego \\u017c\\u0105dania. Pracujemy nad jak najszybszym rozwi\\u0105zaniem.","is_silent":false,"is_transient":false,"requires_reauth":false,"allow_user_retry":false,"debug_info":"Invalid values provided for variables of operation \\"MessengerThreadlist\\": Value \\"Array { 0 => \\"blocked\\" }\\" cannot be used for variable \\"$tags\\": List item #0 has incompatible type with this list: There is no value named \\"blocked\\" in the enum \\"MessagingGraphQLTags\\".","query_path":null,"fbtrace_id":"B35QJcgcuU1"}]}}\r\n                              {\n   "successful_results": 0,\n   "error_results": 1,\n   "skipped_results": 0\n}' }
```

this is how it looks after reformatting:
```json
{
  "o0": {
    "errors": [
      {
        "message": "Invalid values provided for variables of operation \"MessengerThreadlist\": Value \"Array { 0 => \"blocked\" }\" cannot be used for variable \"$tags\": List item #0 has incompatible type with this list: There is no value named \"blocked\" in the enum \"MessagingGraphQLTags\".",
        "severity": "CRITICAL",
        "code": 1675012,
        "api_error_code": null,
        "summary": "Brak możliwości rozpatrzenia prośby",
        "description": "Wystąpił problem w zrealizowaniu Twojego żądania. Pracujemy nad jak najszybszym rozwiązaniem.",
        "is_silent": false,
        "is_transient": false,
        "requires_reauth": false,
        "allow_user_retry": false,
        "debug_info": "Invalid values provided for variables of operation \"MessengerThreadlist\": Value \"Array { 0 => \"blocked\" }\" cannot be used for variable \"$tags\": List item #0 has incompatible type with this list: There is no value named \"blocked\" in the enum \"MessagingGraphQLTags\".",
        "query_path": null,
        "fbtrace_id": "B35QJcgcuU1"
      }
    ]
  }
}
{
  "successful_results": 0,
  "error_results": 1,
  "skipped_results": 0
}
```

`JSON.parse error` is not helpful for users...

I'd like to note that successful request returns an array with two elements...
```json
[
    {
        "o0": {
            "data": {
                ...
            }
        }
    },
    {
        "successful_results": 1,
        "error_results": 0,
        "skipped_results": 0
    }
]
```

**Comment by Schmavery** [comment]
Thanks for fixing!
