### ISSUE TITLE
ESOCKETTIMEDOUT in listen.js

### ISSUE THREAD

**Issue by Bjornskjald** [Schmavery/facebook-chat-api#675]
I've checked #665 and there wasn't any solution to this error.
Basically, every few hours I get this error and the only way to make it work again is to restart the whole bot.
Stacktrace:
```
ERR! listen Error: ESOCKETTIMEDOUT
ERR! listen     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/miscord/node_modules/request/request.js:812:19)
ERR! listen     at Object.onceWrapper (events.js:273:13)
ERR! listen     at ClientRequest.emit (events.js:182:13)
ERR! listen     at TLSSocket.emitTimeout (_http_client.js:706:34)
ERR! listen     at Object.onceWrapper (events.js:273:13)
ERR! listen     at TLSSocket.emit (events.js:182:13)
ERR! listen     at TLSSocket.Socket._onTimeout (net.js:444:8)
ERR! listen     at ontimeout (timers.js:427:11)
ERR! listen     at tryOnTimeout (timers.js:289:5)
ERR! listen     at listOnTimeout (timers.js:252:5)
ERR! listen     at Timer.processTimers (timers.js:212:10)
```
Yes, I do have a stable internet connection. It's hosted on DigitalOcean and I never had any issues with connection on their servers.

**Comment by Bjornskjald** [comment]
I'll try to add it, I have currently 12 bots running so I hope I'll get some results soon

**Comment by Bjornskjald** [comment]
Update: the env variable didn't help.
I'll try the maxSockets option.

**Comment by Schmavery** [comment]
Thanks for testing that.
o.O 12 bots? I'm assuming they're on different accounts? Otherwise I wouldn't be surprised if there was some sort of rate limiting happening.

Honestly I don't really know much about what's happening here and all I'm doing is looking at stackoverflow... https://stackoverflow.com/a/43857814  This one seems to try to set `keepAlive: true` somehow. Could be worth a shot if you can figure it out.

Unfortunately the only other guess I would have is to somehow catch it and optionally try to retry the call (or ignore).

**Comment by Bjornskjald** [comment]
12 bots, each on a different account and split in half to 2 separate servers. I'll try that approach, maybe this time it will work.

**Comment by bobland1** [comment]
any update?
I receive this error too

**Comment by ravkr** [comment]
I've had the same problem few days ago... over 30% of requests were failing
but the same script was working fine (with no changes) after 12 hours :/
I'm wondering is this is a facebook's issue ...

**Comment by Bjornskjald** [comment]
@ravkr Today it probably is a Facebook issue, I'm getting timeouts on servers that never had them...

**Comment by hoc-anms** [comment]
I also have same issue, affter 5h active 1 account
now, how to resolved it??
thanks

**Comment by PixelHir** [comment]
How's this going? I am experiencing same thing as well

**Comment by hoc-anms** [comment]
> How's this going? I am experiencing same thing as well

But it still active, I try on function  api.listen(). It still run ok.

**Comment by japaodsc** [comment]
`0|Bot    |  login Error: connect ECONNREFUSED 31.13.82.36:443
0|Bot    | ERR! login     at Object._errnoException (util.js:1022:11)
0|Bot    | ERR! login     at _exceptionWithHostPort (util.js:1044:20)
0|Bot    | ERR! login     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
0|Bot    | ERR! login
0|Bot    |   { Error: connect ECONNREFUSED 31.13.82.36:443
0|Bot    | ERR! 
0|Bot    | login     at Object._errnoException (util.js:1022:11)
0|Bot    | ERR!
0|Bot    |  login
0|Bot    |      at _exceptionWithHostPort (util.js:1044:20)
0|Bot    | ERR! login     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
0|Bot    | ERR!
0|Bot    |  login   cause: 
0|Bot    | ERR! login    { Error: connect ECONNREFUSED 31.13.82.36:443
0|Bot    | ERR! login     at Object._errnoException (util.js:1022:11)
0|Bot    | ERR! login     at _exceptionWithHostPort (util.js:1044:20)
0|Bot    | ERR! login
0|Bot    |      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
0|Bot    | ERR!
0|Bot    |  login      code: 'ECONNREFUSED',
0|Bot    | ERR! 
0|Bot    | login      errno: 'ECONNREFUSED',
0|Bot    | ERR! login
0|Bot    |       syscall: 'connect',
0|Bot    | ERR! login
0|Bot    |       address: '31.13.82.36',
0|Bot    | ERR! login      port: 443 },
0|Bot    | ERR!
0|Bot    |  login
0|Bot    |    isOperational: true,
0|Bot    | ERR! login   code: 'ECONNREFUSED',
0|Bot    | ERR! login   errno: 'ECONNREFUSED',
0|Bot    | ERR! login   syscall: 'connect',
0|Bot    | ERR!
0|Bot    |  login   address: '31.13.82.36',
0|Bot    | ERR! login   port: 443 }`
Hi, I'm having this error today. Is this some kind of fb error?
