### ISSUE TITLE
Can't retrieve ThreadList - Can't read property 'error_results' of undefined

### ISSUE THREAD

**Issue by vucodil** [Schmavery/facebook-chat-api#679]
I can't retrieve ThreadList due to a TypeError in src/getThreadList.js:195

Any ideas about this bug ?

```
ERR! getThreadList TypeError: Cannot read property 'error_results' of undefined
ERR! getThreadList     at defaultFuncs.post.then.then (/home/lambda/facebook-chat-api/src/getThreadList.js:195:41)
ERR! getThreadList     at tryCatcher (/home/lambda/Applications/Facebridge/FacebookBot/node_modules/bluebird/js/main/util.js:26:23)
...
```

**Comment by vucodil** [comment]
I think that it is linked to the recurring error #202. It occurs after sometimes and it works flawlessly when I restart the bot. I also get the 1357004 error just before getting the TypeError. 

I keep it open as the #202 error is still closed

**Comment by ermay12** [comment]
Hi was this issue ever resolved?  I am also getting "Cannot read property 'error_results' of undefined" when i call this function.  Restarting the bot doesn't fix it as mentioned above.
