### ISSUE TITLE
Problem retrieving thread information of getThreadInfo

### ISSUE THREAD

**Issue by ChienDevIT** [Schmavery/facebook-chat-api#687]
Today I have encountered this error, and I do not know how to overcome it.

```
ERR! getThreadInfoGraphQL TypeError: Cannot read property 'thread_key' of null
ERR! getThreadInfoGraphQL     at formatThreadGraphQLResponse (/home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:35:31)
ERR! getThreadInfoGraphQL     at /home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
ERR! getThreadInfoGraphQL     at tryCatcher (/home/ubuntu/workspace/node_modules/bluebird/js/main/util.js:26:23)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getThreadInfoGraphQL     at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:700:14)
ERR! getThreadInfoGraphQL     at Async._drainQueue (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:123:16)
ERR! getThreadInfoGraphQL     at Async._drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:133:10)
ERR! getThreadInfoGraphQL     at Immediate.Async.drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:15:14)
ERR! getThreadInfoGraphQL     at runCallback (timers.js:672:20)
ERR! getThreadInfoGraphQL     at tryOnImmediate (timers.js:645:5)
ERR! getThreadInfoGraphQL     at processImmediate [as _immediateCallback] (timers.js:617:5)
ERR! getThreadInfoGraphQL  TypeError: Cannot read property 'thread_key' of null
ERR! getThreadInfoGraphQL     at formatThreadGraphQLResponse (/home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:35:31)
ERR! getThreadInfoGraphQL     at /home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
ERR! getThreadInfoGraphQL     at tryCatcher (/home/ubuntu/workspace/node_modules/bluebird/js/main/util.js:26:23)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getThreadInfoGraphQL     at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:700:14)
ERR! getThreadInfoGraphQL     at Async._drainQueue (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:123:16)
ERR! getThreadInfoGraphQL     at Async._drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:133:10)
ERR! getThreadInfoGraphQL     at Immediate.Async.drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:15:14)
ERR! getThreadInfoGraphQL     at runCallback (timers.js:672:20)
ERR! getThreadInfoGraphQL     at tryOnImmediate (timers.js:645:5)
ERR! getThreadInfoGraphQL     at processImmediate [as _immediateCallback] (timers.js:617:5)
TypeError: Cannot read property 'thread_key' of null
    at formatThreadGraphQLResponse (/home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:35:31)
    at /home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
    at tryCatcher (/home/ubuntu/workspace/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
info listen Got answer in 2384
info listen Got answer in 437
ERR! getThreadInfoGraphQL TypeError: Cannot read property 'thread_key' of null
ERR! getThreadInfoGraphQL     at formatThreadGraphQLResponse (/home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:35:31)
ERR! getThreadInfoGraphQL     at /home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
ERR! getThreadInfoGraphQL     at tryCatcher (/home/ubuntu/workspace/node_modules/bluebird/js/main/util.js:26:23)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getThreadInfoGraphQL     at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:700:14)
ERR! getThreadInfoGraphQL     at Async._drainQueue (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:123:16)
ERR! getThreadInfoGraphQL     at Async._drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:133:10)
ERR! getThreadInfoGraphQL     at Immediate.Async.drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:15:14)
ERR! getThreadInfoGraphQL     at runCallback (timers.js:672:20)
ERR! getThreadInfoGraphQL     at tryOnImmediate (timers.js:645:5)
ERR! getThreadInfoGraphQL     at processImmediate [as _immediateCallback] (timers.js:617:5)
ERR! getThreadInfoGraphQL  TypeError: Cannot read property 'thread_key' of null
ERR! getThreadInfoGraphQL     at formatThreadGraphQLResponse (/home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:35:31)
ERR! getThreadInfoGraphQL     at /home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
ERR! getThreadInfoGraphQL     at tryCatcher (/home/ubuntu/workspace/node_modules/bluebird/js/main/util.js:26:23)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getThreadInfoGraphQL     at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:700:14)
ERR! getThreadInfoGraphQL     at Async._drainQueue (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:123:16)
ERR! getThreadInfoGraphQL     at Async._drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:133:10)
ERR! getThreadInfoGraphQL     at Immediate.Async.drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:15:14)
ERR! getThreadInfoGraphQL     at runCallback (timers.js:672:20)
ERR! getThreadInfoGraphQL     at tryOnImmediate (timers.js:645:5)
ERR! getThreadInfoGraphQL     at processImmediate [as _immediateCallback] (timers.js:617:5)
TypeError: Cannot read property 'thread_key' of null
    at formatThreadGraphQLResponse (/home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:35:31)
    at /home/ubuntu/workspace/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
    at tryCatcher (/home/ubuntu/workspace/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/ubuntu/workspace/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

And this is my code

```
api.listen(function(err, event) {
			if (err) return console.error(err);
			api.getThreadInfo(event.threadID, function(err, thread) {
				if (err) return console.error(err);
				api.getUserInfo(event.senderID, function(err, user) {
					user = firstElement(user);
					if (!!user) user.id = event.senderID;
					if (err) return console.error(err);
					console.log(event);
					switch (event.type) {
						case "message":
							eventMsg(api, event, thread, user, me);
							break;
						case "event":
							eventEvent(api, event, thread, user, me);
							break;
						case "typ":
							break;
						case "read":
							break;
						case "read_receipt":
							break;
						case "message_reaction":
							eventReaction(api, event, thread, user, me);
							break;
						case "presence":
							break;
					}
				});
			});
		});
```

I hope someone tells me how to fix it. Thanks !

**Comment by ravkr** [comment]
Are you using npm version or github (bleeding edge) version?

**Comment by ChienDevIT** [comment]
```
chien@ubuntu:~ $ node -v
v10.11.0
chien@ubuntu:~ $ npm -v
6.4.1
```

**Comment by ChienDevIT** [comment]
package.json
```
{
  "name": "chatbot",
  "version": "1.0.0",
  "description": "",
  "main": "bot.js",
  "repository": "",
  "author": "Nguyen Duc Chien <chiendevit@gmail.com>",
  "dependencies": {
    "moment": "^2.22.2",
    "facebook-chat-api": "^1.6.0"
  },
  "scripts": {
    "start": "node bot.js"
  }
}

```

**Comment by ChienDevIT** [comment]
I think this is a similar case: https://github.com/mjkaufer/Messer/issues/67

**Comment by ChienDevIT** [comment]
Thank you. I found the error myself, thank you for reading
