### ISSUE TITLE
Multithread?

### ISSUE THREAD

**Issue by bezvozni** [Schmavery/facebook-chat-api#692]
Hello. I try run it for two account. I use cluster module. 
Can i get any way solution for this problem:
```
WARN parseAndCheckLogin Got status code 502 - 1. attempt to retry in 513 milliseconds...
WARN parseAndCheckLogin Got status code 502 - 2. attempt to retry in 4531 milliseconds...
ERR! listen Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
ERR! listen     at C:\Users\Илья\Desktop\FBTG\node_modules\facebook-chat-api\utils.js:1055:15
ERR! listen     at tryCatcher (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Function.Promise.attempt.Promise.try (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\method.js:31:24)
ERR! listen     at C:\Users\Илья\Desktop\FBTG\node_modules\facebook-chat-api\utils.js:1002:24
ERR! listen     at tryCatcher (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\promise.js:584:18)
ERR! listen     at Async._drainQueue (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\async.js:128:12)
ERR! listen     at Async._drainQueues (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (C:\Users\Илья\Desktop\FBTG\node_modules\bluebird\js\main\async.js:15:14)
ERR! listen     at runCallback (timers.js:810:20)
ERR! listen     at tryOnImmediate (timers.js:768:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:745:5)
```
Maybe for someone it clearly?
Bot only listens.

**Comment by bezvozni** [comment]
Solution: increase retryTime value in utils.js =))

**Comment by Schmavery** [comment]
If it's a simple timeout increase or something that won't affect anything else feel free to make a PR.
