### ISSUE TITLE
LogIn Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Akshansh93** [Schmavery/facebook-chat-api#703]
I am able to logIn from my local browser and using an email as username. But when I try to login using the sdk from my ubuntu server (`Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64)`), I got following error:
```
ERR! login Error: unable to get local issuer certificate
ERR! login     at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
ERR! login     at emitNone (events.js:105:13)
ERR! login     at TLSSocket.emit (events.js:207:7)
ERR! login     at TLSSocket._finishInit (_tls_wrap.js:628:8)
ERR! login     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
ERR! login  { Error: unable to get local issuer certificate
ERR! login     at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
ERR! login     at emitNone (events.js:105:13)
ERR! login     at TLSSocket.emit (events.js:207:7)
ERR! login     at TLSSocket._finishInit (_tls_wrap.js:628:8)
ERR! login     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
ERR! login   cause:
ERR! login    { Error: unable to get local issuer certificate
ERR! login        at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
ERR! login        at emitNone (events.js:105:13)
ERR! login        at TLSSocket.emit (events.js:207:7)
ERR! login        at TLSSocket._finishInit (_tls_wrap.js:628:8)
ERR! login        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' },
ERR! login   isOperational: true,
ERR! login   code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
```
I am already using "forceLogin=true". 
It is referring to which certificate?
Is it something that is downloaded automatically or I have to download it manually?
If manual download should be done then from where should I get this certificate?

**Comment by Schmavery** [comment]
Some sort of SSL issue on your machine? Never seen this.

**Comment by bsansouci** [comment]
Maybe related https://github.com/nodejs/node/issues/3742
