### ISSUE TITLE
BadRequestError: request aborted

### ISSUE THREAD

**Issue by xnerhu** [Schmavery/facebook-chat-api#722]
Hello. I have this error after a couple of hours.

```bash
0|server   |     at TCP._handle.close (net.js:600:12)
0|server   | BadRequestError: request aborted
0|server   |     at IncomingMessage.onAborted (/path/node_modules/raw-body/index.js:231:10)
0|server   |     at IncomingMessage.emit (events.js:189:13)
0|server   |     at abortIncoming (_http_server.js:449:9)
0|server   |     at socketOnClose (_http_server.js:442:3)
0|server   |     at Socket.emit (events.js:194:15)
0|server   |     at TCP._handle.close (net.js:600:12)
0|server   | BadRequestError: request aborted
0|server   |     at IncomingMessage.onAborted (/path/node_modules/raw-body/index.js:231:10)
0|server   |     at IncomingMessage.emit (events.js:189:13)
0|server   |     at abortIncoming (_http_server.js:449:9)
0|server   |     at socketOnClose (_http_server.js:442:3)
0|server   |     at Socket.emit (events.js:194:15)
0|server   |     at TCP._handle.close (net.js:600:12)
```

**Comment by lequanglam** [comment]
That error comes from module stream-utils/rawbody, not this package.
