### ISSUE TITLE
sendMessage failed with new Facebook response Apr 2019

### ISSUE THREAD

**Issue by royalgarter** [Schmavery/facebook-chat-api#726]
Since 26-Apr-2019, I got error from the sendMessage function

`ERR! sendMessage TypeError: Cannot read property 'reduce' of undefined
ERR! sendMessage   at d:\GIT\addons\node_modules\facebook-chat-api\src\sendMessage.js:159:51
ERR! sendMessage   at tryCatcher (d:\GIT\addons\node_modules\facebook-chat-api\node_modules\bluebird\js\main\util.js:26:23)
ERR! sendMessage   at Promise._settlePromiseFromHandler (d:\GIT\addons\node_modules\facebook-chat-api\node_modules\bluebird\js\main\promise.js:510:31)
ERR! sendMessage   at Promise._settlePromiseAt (d:\GIT\addons\node_modules\facebook-chat-api\node_modules\bluebird\js\main\promise.js:584:18)
ERR! sendMessage   at Promise._settlePromises (d:\GIT\addons\node_modules\facebook-chat-api\node_modules\bluebird\js\main\promise.js:700:14)
ERR! sendMessage   at Async._drainQueue (d:\GIT\addons\node_modules\facebook-chat-api\node_modules\bluebird\js\main\async.js:123:16)
ERR! sendMessage   at Async._drainQueues (d:\GIT\addons\node_modules\facebook-chat-api\node_modules\bluebird\js\main\async.js:133:10)
ERR! sendMessage   at Immediate.Async.drainQueues (d:\GIT\addons\node_modules\facebook-chat-api\node_modules\bluebird\js\main\async.js:15:14)
ERR! sendMessage   at runCallback (timers.js:810:20)
ERR! sendMessage   at tryOnImmediate (timers.js:768:5)
ERR! sendMessage   at processImmediate [as _immediateCallback] (timers.js:745:5)`

after debuggin, here's the new response

`{"__ar":1,"payload":[],"jsmods":{"require":[["ServerRedirect","redirectPageTo",[],["/checkpoint/block/",true,false]]],"define":[["cr:794450",["FBLoggerImpl"],{"__rc":["FBLoggerImpl","Aa2_lC4XCrQzc96mmwaz_4zV4LnpqvkRQXU36Y_v7SSAQORystOY__274Gmp5VlSfEdUAR1r2a9GS_Q2bKp2-ow"]},-1],["KSConfig",[],{"killed":{"__set":["POCKET_MONSTERS_CREATE","POCKET_MONSTERS_DELETE","VIDEO_DIMENSIONS_FROM_PLAYER_IN_UPLOAD_DIALOG","PREVENT_INFINITE_URL_REDIRECT","POCKET_MONSTERS_UPDATE_NAME","ADS_PLACEMENT_FIX_PUBLISHER_PLATFORMS_MUTATION","MOBILITY_KILL_OLD_VISIBILITY_POSITION_SETTING","WORKPLACE_DISPLAY_TEXT_EVIDENCE_REPORTING","TEAM_VC_PORTAL"]}},2580],["UriNeedRawQuerySVConfig",[],{"uris":["dms.netmng.com","doubleclick.net","r.msn.com","watchit.sky.com","graphite.instagram.com","www.kfc.co.th","learn.pantheon.io","www.landmarkshops.in","www.ncl.com","s0.wp.com","www.tatacliq.com","bs.serving-sys.com","kohls.com","lazada.co.th","xg4ken.com","technopark.ru","officedepot.com.mx","bestbuy.com.mx"]},3871]]},"js":["o0H6F","nbe4U"],"bootloadable":{},"resource_map":{"o0H6F":{"type":"js","src":"https://static.xx.fbcdn.net/rsrc.php/v3imOT4/yF/l/vi_VN/obXi42EeRrh.js"},"nbe4U":{"type":"js","src":"https://static.xx.fbcdn.net/rsrc.php/v3iOLN4/yz/l/vi_VN/JEnrrrE7eNv.js"}},"ixData":{},"bxData":{},"gkxData":{},"qexData":{},"lid":"6684158526600483277"}`

the REAL NEW response from the messenger.com 

`for (;;);{"__ar":1,"payload":{"actions":[{"thread_id":"","thread_fbid":"207622609582583","other_user_fbid":"","action_type":"ma-type:send-message","client_thread_id":null,"message_id":"mid.$gAAC81OfkOfdwip3Yc1qWViRODWbw","client_message_id":"6527499423848425200","status":1,"timestamp":1556277137505,"attachments":[],"graphql_payload":null,"for_page":false}],"payload_source":"server_send_message"},"bootloadable":{},"ixData":{},"bxData":{},"gkxData":{},"qexData":{},"lid":"6684159407185632080"}`

**Comment by royalgarter** [comment]
This was my mistake on login process. Please ignore it, thank you.
