### ISSUE TITLE
Some of newly created accounts seem to stop working

### ISSUE THREAD

**Issue by PixelHir** [Schmavery/facebook-chat-api#741]
Recently I changed the bot's account to a new one and after this no matter what i do it always throws an error.

When sending message:
```
ERR! sendMessage TypeError: Cannot read property 'reduce' of undefined
ERR! sendMessage     at /root/zlecenie-1/node_modules/facebook-chat-api/src/sendMessage.js:157:51
ERR! sendMessage     at tryCatcher (/root/zlecenie-1/node_modules/bluebird/js/main/util.js:26:23)
ERR! sendMessage     at Promise._settlePromiseFromHandler (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:510:31)
ERR! sendMessage     at Promise._settlePromiseAt (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:584:18)
ERR! sendMessage     at Promise._settlePromises (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:700:14)
ERR! sendMessage     at Async._drainQueue (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:123:16)
ERR! sendMessage     at Async._drainQueues (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:133:10)
ERR! sendMessage     at Immediate.Async.drainQueues [as _onImmediate] (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:15:14)
ERR! sendMessage     at runCallback (timers.js:705:18)
ERR! sendMessage     at tryOnImmediate (timers.js:676:5)
ERR! sendMessage     at processImmediate (timers.js:658:5)
ERR! sendMessage     at process.topLevelDomainCallback (domain.js:120:23)
ERR! sendMessage  TypeError: Cannot read property 'reduce' of undefined
ERR! sendMessage     at /root/zlecenie-1/node_modules/facebook-chat-api/src/sendMessage.js:157:51
ERR! sendMessage     at tryCatcher (/root/zlecenie-1/node_modules/bluebird/js/main/util.js:26:23)
ERR! sendMessage     at Promise._settlePromiseFromHandler (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:510:31)
ERR! sendMessage     at Promise._settlePromiseAt (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:584:18)
ERR! sendMessage     at Promise._settlePromises (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:700:14)
ERR! sendMessage     at Async._drainQueue (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:123:16)
ERR! sendMessage     at Async._drainQueues (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:133:10)
ERR! sendMessage     at Immediate.Async.drainQueues [as _onImmediate] (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:15:14)
ERR! sendMessage     at runCallback (timers.js:705:18)
ERR! sendMessage     at tryOnImmediate (timers.js:676:5)
ERR! sendMessage     at processImmediate (timers.js:658:5)
ERR! sendMessage     at process.topLevelDomainCallback (domain.js:120:23)
{}
ERR! getThreadInfoGraphQL TypeError: Cannot read property 'error_results' of undefined
ERR! getThreadInfoGraphQL     at /root/zlecenie-1/node_modules/facebook-chat-api/src/getThreadInfo.js:159:41
ERR! getThreadInfoGraphQL     at tryCatcher (/root/zlecenie-1/node_modules/bluebird/js/main/util.js:26:23)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseFromHandler (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseAt (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getThreadInfoGraphQL     at Promise._settlePromises (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:700:14)
ERR! getThreadInfoGraphQL     at Async._drainQueue (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:123:16)
ERR! getThreadInfoGraphQL     at Async._drainQueues (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:133:10)
ERR! getThreadInfoGraphQL     at Immediate.Async.drainQueues [as _onImmediate] (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:15:14)
ERR! getThreadInfoGraphQL     at runCallback (timers.js:705:18)
ERR! getThreadInfoGraphQL     at tryOnImmediate (timers.js:676:5)
ERR! getThreadInfoGraphQL     at processImmediate (timers.js:658:5)
ERR! getThreadInfoGraphQL     at process.topLevelDomainCallback (domain.js:120:23)
ERR! getThreadInfoGraphQL  TypeError: Cannot read property 'error_results' of undefined
ERR! getThreadInfoGraphQL     at /root/zlecenie-1/node_modules/facebook-chat-api/src/getThreadInfo.js:159:41
ERR! getThreadInfoGraphQL     at tryCatcher (/root/zlecenie-1/node_modules/bluebird/js/main/util.js:26:23)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseFromHandler (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getThreadInfoGraphQL     at Promise._settlePromiseAt (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getThreadInfoGraphQL     at Promise._settlePromises (/root/zlecenie-1/node_modules/bluebird/js/main/promise.js:700:14)
ERR! getThreadInfoGraphQL     at Async._drainQueue (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:123:16)
ERR! getThreadInfoGraphQL     at Async._drainQueues (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:133:10)
ERR! getThreadInfoGraphQL     at Immediate.Async.drainQueues [as _onImmediate] (/root/zlecenie-1/node_modules/bluebird/js/main/async.js:15:14)
ERR! getThreadInfoGraphQL     at runCallback (timers.js:705:18)
ERR! getThreadInfoGraphQL     at tryOnImmediate (timers.js:676:5)
ERR! getThreadInfoGraphQL     at processImmediate (timers.js:658:5)
ERR! getThreadInfoGraphQL     at process.topLevelDomainCallback (domain.js:120:23)
```

**Comment by PixelHir** [comment]
nevermind, seems like an issue with account verification
