### ISSUE TITLE
changeBlockedStatus yields Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.

### ISSUE THREAD

**Issue by dreamflasher** [Schmavery/facebook-chat-api#770]
```
api.changeBlockedStatus(d.userID, true, (err) => {
                if(err) return console.error(err);
            });
```

yields 

```
Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /root/node_modules/facebook-chat-api/utils.js:1042:15
    at tryCatcher (/root/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/root/node_modules/bluebird/js/main/method.js:31:24)
    at /root/node_modules/facebook-chat-api/utils.js:989:24
    at tryCatcher (/root/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/root/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/root/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/root/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/root/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/root/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/root/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

I am getting the userID from the result of getFriendsList, so this call works and it shows me an actual user I am friends with.

**Comment by adiantek** [comment]
changeThreadEmoji also:

```
ERR! changeThreadEmoji  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! changeThreadEmoji     at D:\git\fbapi\node_modules\facebook-chat-api\utils.js:1042:15
ERR! changeThreadEmoji     at tryCatcher (D:\git\fbapi\node_modules\bluebird\js\main\util.js:26:23)
ERR! changeThreadEmoji     at Function.Promise.attempt.Promise.try (D:\git\fbapi\node_modules\bluebird\js\main\method.js:31:24)
ERR! changeThreadEmoji     at D:\git\fbapi\node_modules\facebook-chat-api\utils.js:989:24
ERR! changeThreadEmoji     at tryCatcher (D:\git\fbapi\node_modules\bluebird\js\main\util.js:26:23)
ERR! changeThreadEmoji     at Promise._settlePromiseFromHandler (D:\git\fbapi\node_modules\bluebird\js\main\promise.js:510:31)
ERR! changeThreadEmoji     at Promise._settlePromiseAt (D:\git\fbapi\node_modules\bluebird\js\main\promise.js:584:18)
ERR! changeThreadEmoji     at Async._drainQueue (D:\git\fbapi\node_modules\bluebird\js\main\async.js:128:12)
ERR! changeThreadEmoji     at Async._drainQueues (D:\git\fbapi\node_modules\bluebird\js\main\async.js:133:10)
ERR! changeThreadEmoji     at Immediate.Async.drainQueues [as _onImmediate] (D:\git\fbapi\node_modules\bluebird\js\main\async.js:15:14)
ERR! changeThreadEmoji     at runCallback (timers.js:705:18)
ERR! changeThreadEmoji     at tryOnImmediate (timers.js:676:5)
ERR! changeThreadEmoji     at processImmediate (timers.js:658:5)
```

**Comment by prameshbajra** [comment]
Found any solution to this?
