### ISSUE TITLE
 api.getFriendsList [ERROR!]

### ISSUE THREAD

**Issue by Theblood** [Schmavery/facebook-chat-api#783]
```
> WARN parseAndCheckLogin Got status code 500 - 1. attempt to retry in 2805 milliseconds...
ERR! getFriendsList Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! getFriendsList     at /home/theblood/olaf-bot/node_modules/facebook-chat-api/utils.js:1042:15
ERR! getFriendsList     at tryCatcher (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! getFriendsList     at Function.Promise.attempt.Promise.try (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
ERR! getFriendsList     at /home/theblood/olaf-bot/node_modules/facebook-chat-api/utils.js:989:24
ERR! getFriendsList     at tryCatcher (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! getFriendsList     at Promise._settlePromiseFromHandler (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getFriendsList     at Promise._settlePromiseAt (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getFriendsList     at Async._drainQueue (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:128:12)
ERR! getFriendsList     at Async._drainQueues (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! getFriendsList     at Immediate.Async.drainQueues [as _onImmediate] (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! getFriendsList     at runCallback (timers.js:705:18)
ERR! getFriendsList     at tryOnImmediate (timers.js:676:5)
ERR! getFriendsList     at processImmediate (timers.js:658:5)
ERR! getFriendsList  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! getFriendsList     at /home/theblood/olaf-bot/node_modules/facebook-chat-api/utils.js:1042:15
ERR! getFriendsList     at tryCatcher (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! getFriendsList     at Function.Promise.attempt.Promise.try (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
ERR! getFriendsList     at /home/theblood/olaf-bot/node_modules/facebook-chat-api/utils.js:989:24
ERR! getFriendsList     at tryCatcher (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! getFriendsList     at Promise._settlePromiseFromHandler (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
ERR! getFriendsList     at Promise._settlePromiseAt (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
ERR! getFriendsList     at Async._drainQueue (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:128:12)
ERR! getFriendsList     at Async._drainQueues (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! getFriendsList     at Immediate.Async.drainQueues [as _onImmediate] (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! getFriendsList     at runCallback (timers.js:705:18)
ERR! getFriendsList     at tryOnImmediate (timers.js:676:5)
ERR! getFriendsList     at processImmediate (timers.js:658:5)
Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /home/theblood/olaf-bot/node_modules/facebook-chat-api/utils.js:1042:15
    at tryCatcher (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
    at /home/theblood/olaf-bot/node_modules/facebook-chat-api/utils.js:989:24
    at tryCatcher (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/theblood/olaf-bot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
someone has the following error

**Comment by Theblood** [comment]
@Schmavery help me :C

**Comment by lequanglam** [comment]
look like facebook is changing API.

**Comment by lukyrys** [comment]
same error as #782
