### ISSUE TITLE
Error after successfully connected

### ISSUE THREAD

**Issue by Henri2h** [Schmavery/facebook-chat-api#804]
Using the last version of facebook-chat-api pulled directly from github, I have this issue.
It was working during three days and broke this morning or yesterday evening.

```
error : 2020-04-02T12:38:48.277Z : Listening : errorCannot read property 'successful_results' of undefined

Unhandled rejection ReferenceError: error is not defined
    at /home/henri2h/UbTouchMessBridge/index.js:139:37
    at /home/henri2h/UbTouchMessBridge/node_modules/facebook-chat-api/src/listenMqtt.js:544:16
    at tryCatcher (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/henri2h/UbTouchMessBridge/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

This is the result of resData in defaultFuncs (line 524 of listenMqtt) :
```
{
  __ar: 1,
  error: 1357004,
  errorSummary: 'Nos paenitet aliquid errasse.',
  errorDescription: 'Please try closing and re-opening your browser window.',
  payload: null,
  bootloadable: {},
  ixData: {},
  bxData: {},
  gkxData: {},
  qexData: {},
  lid: '6811099725441203910'
}
```
Nos paenitet aliquid errasse = Unfortunately, something was wrong (just because we can set facebook language to latin :) )

Don't know what's really going here...
Potential duplicate of https://github.com/Schmavery/facebook-chat-api/issues/202, if this is the case, I'm sorry. Tell me and I will post this issue in the correct thread.

**Comment by 7osCraft** [comment]
Could you try logging in again with the email and password?

**Comment by Henri2h** [comment]
I have done so, and it doesn't work neither

**Comment by Henri2h** [comment]
If that could be of any use, here is my code : https://github.com/Henri2h/UbTouchMessBridge

**Comment by 7osCraft** [comment]
Your code looks fine.
You could try these things to see if the problem disappears:
-Change the user agent.
-Change the account's password.
-Try a different account.

**Comment by Henri2h** [comment]
Well, changing the user agent to default one, worked.
Thanks for the help !!

**Comment by Schmavery** [comment]
Should we change this library's user agent?

**Comment by 7osCraft** [comment]
I guess we should
