### ISSUE TITLE
Does not login at all

### ISSUE THREAD

**Issue by DavidGOrtega** [Schmavery/facebook-chat-api#812]
```js
login({email: '*********, password: '********'}, (err, api) => {
    if(err) return console.error(err);

    api.listen((err, message) => {
      api.sendMessage(message.body, message.threadID);
    });
});
```

```
info login Logging in...
info login Logged in
info login Request to reconnect
info login Done logging in.
ERR! listen Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! listen     at /node_modules/facebook-chat-api/utils.js:1042:15
ERR! listen     at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by japaodsc** [comment]
Please use api.listenMqtt

> ```js
> login({email: '*********, password: '********'}, (err, api) => {
>     if(err) return console.error(err);
> 
>     api.listen((err, message) => {
>       api.sendMessage(message.body, message.threadID);
>     });
> });
> ```
> 
> ```
> info login Logging in...
> info login Logged in
> info login Request to reconnect
> info login Done logging in.
> ERR! listen Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
> ERR! listen     at /node_modules/facebook-chat-api/utils.js:1042:15
> ERR! listen     at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
> ```
