### ISSUE TITLE
404 When Running Listen Example

### ISSUE THREAD

**Issue by cts5ws** [Schmavery/facebook-chat-api#816]
I'm trying out some example code from the README
```
const login = require("facebook-chat-api");

login({email: "***", password: "***"},
    (err, api) => {
    if(err) return console.error(err);

    api.listen((err, message) => {
        if(err) return console.error(err);
        // api.sendMessage(message.body, message.threadID);
        console.log(message.body);
    });
});
```

and getting the following error

```
info login Logging in...
info login Logged in
info login Request to reconnect
info login Done logging in.
ERR! listen Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! listen     at /Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/facebook-chat-api/utils.js:1042:15
ERR! listen     at tryCatcher (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/util.js:16:23)
ERR! listen     at Function.Promise.attempt.Promise.try (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/method.js:39:29)
ERR! listen     at /Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/facebook-chat-api/utils.js:989:24
ERR! listen     at tryCatcher (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/util.js:16:23)
ERR! listen     at Promise._settlePromiseFromHandler (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:548:31)
ERR! listen     at Promise._settlePromise (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:605:18)
ERR! listen     at Promise._settlePromise0 (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:650:10)
ERR! listen     at Promise._settlePromises (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:730:18)
ERR! listen     at Promise._fulfill (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:674:18)
ERR! listen     at Promise._resolveCallback (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:467:57)
ERR! listen     at Promise._settlePromiseFromHandler (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:560:17)
ERR! listen     at Promise._settlePromise (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:605:18)
ERR! listen     at Promise._settlePromise0 (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:650:10)
ERR! listen     at Promise._settlePromises (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:730:18)
ERR! listen     at Promise._fulfill (/Users/cschafer/Desktop/personal/code/repo/messagerouter/messengerclient/node_modules/bluebird/js/release/promise.js:674:18)
ERR! listen  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
```

Any idea what the issue is? Seems like something isn't aligned with what FB is expecting.

**Comment by lequanglam** [comment]
use `listenMqtt`, thanks.

**Comment by cts5ws** [comment]
ah thanks
