### ISSUE TITLE
Facebook always blocks my account when I try to log in

### ISSUE THREAD

**Issue by gitFoxCode** [Schmavery/facebook-chat-api#829]
my code: 
```javascript
const login = require("facebook-chat-api");

// Create simple echo bot
login({email: "***", password: "***"}, (err, api) => {
    if(err) return console.error(err);

    api.listen((err, message) => {
        api.sendMessage(message.body, message.threadID);
    });
});
```

error:
```batch
info login Logging in...
info login Logged in
info login Request to reconnect
info login Done logging in.
ERR! listen Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! listen     at C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\facebook-chat-api\utils.js:1042:15
ERR! listen     at tryCatcher (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\util.js:16:23)
ERR! listen     at Function.Promise.attempt.Promise.try (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\method.js:39:29)
ERR! listen     at C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\facebook-chat-api\utils.js:989:24
ERR! listen     at tryCatcher (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\util.js:16:23)
ERR! listen     at Promise._settlePromiseFromHandler (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:547:31)
ERR! listen     at Promise._settlePromise (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:649:10)
ERR! listen     at Promise._settlePromises (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:729:18)
ERR! listen     at Promise._fulfill (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:673:18)
ERR! listen     at Promise._resolveCallback (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:466:57)
ERR! listen     at Promise._settlePromiseFromHandler (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:559:17)
ERR! listen     at Promise._settlePromise (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:649:10)
ERR! listen     at Promise._settlePromises (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:729:18)
ERR! listen     at Promise._fulfill (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:673:18)
ERR! listen  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! listen     at C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\facebook-chat-api\utils.js:1042:15
ERR! listen     at tryCatcher (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\util.js:16:23)
ERR! listen     at Function.Promise.attempt.Promise.try (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\method.js:39:29)
ERR! listen     at C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\facebook-chat-api\utils.js:989:24
ERR! listen     at tryCatcher (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\util.js:16:23)
ERR! listen     at Promise._settlePromiseFromHandler (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:547:31)
ERR! listen     at Promise._settlePromise (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:649:10)
ERR! listen     at Promise._settlePromises (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:729:18)
ERR! listen     at Promise._fulfill (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:673:18)
ERR! listen     at Promise._resolveCallback (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:466:57)
ERR! listen     at Promise._settlePromiseFromHandler (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:559:17)
ERR! listen     at Promise._settlePromise (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:649:10)
ERR! listen     at Promise._settlePromises (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:729:18)
ERR! listen     at Promise._fulfill (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:673:18)
Unhandled rejection TypeError: Cannot read property 'body' of undefined
    at api.listen (C:\Users\foxcode\Documents\programming\foxbot testy\basics\bot.js:8:33)
    at C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\facebook-chat-api\src\listen.js:536:11
    at tryCatcher (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\foxcode\Documents\programming\foxbot testy\basics\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
When I enter my account manually, a verification window appears and immediately afterwards I have to change my password. How can I get around this?

**Comment by lequanglam** [comment]
use `api.listenMqtt`, not `api.listen`.

**Comment by gitFoxCode** [comment]
@lequanglam It works! but only when I run the bot locally, when facebook sees the server locations from heroku, it immediately blocks the account

**Comment by qral** [comment]
I was blocked anyway, from my VPS..it's sooner or later ;)

**Comment by Schmavery** [comment]
#852
