### ISSUE TITLE
Error with example echo script

### ISSUE THREAD

**Issue by Dnick421** [Schmavery/facebook-chat-api#843]
info login Logging in...
info login Logged in
info login Request to reconnect
info login Done logging in.
ERR! listen Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! listen     at /home/dnick/node_modules/facebook-chat-api/utils.js:1042:15
ERR! listen     at tryCatcher (/home/dnick/node_modules/bluebird/js/release/util.js:16:23)
ERR! listen     at Function.Promise.attempt.Promise.try (/home/dnick/node_modules/bluebird/js/release/method.js:39:29)
ERR! listen     at /home/dnick/node_modules/facebook-chat-api/utils.js:989:24
ERR! listen     at tryCatcher (/home/dnick/node_modules/bluebird/js/release/util.js:16:23)
ERR! listen     at Promise._settlePromiseFromHandler (/home/dnick/node_modules/bluebird/js/release/promise.js:547:31)
ERR! listen     at Promise._settlePromise (/home/dnick/node_modules/bluebird/js/release/promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (/home/dnick/node_modules/bluebird/js/release/promise.js:649:10)
ERR! listen     at Promise._settlePromises (/home/dnick/node_modules/bluebird/js/release/promise.js:729:18)
ERR! listen     at Promise._fulfill (/home/dnick/node_modules/bluebird/js/release/promise.js:673:18)
ERR! listen     at Promise._resolveCallback (/home/dnick/node_modules/bluebird/js/release/promise.js:466:57)
ERR! listen     at Promise._settlePromiseFromHandler (/home/dnick/node_modules/bluebird/js/release/promise.js:559:17)
ERR! listen     at Promise._settlePromise (/home/dnick/node_modules/bluebird/js/release/promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (/home/dnick/node_modules/bluebird/js/release/promise.js:649:10)
ERR! listen     at Promise._settlePromises (/home/dnick/node_modules/bluebird/js/release/promise.js:729:18)
ERR! listen     at Promise._fulfill (/home/dnick/node_modules/bluebird/js/release/promise.js:673:18)
ERR! listen  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! listen     at /home/dnick/node_modules/facebook-chat-api/utils.js:1042:15
ERR! listen     at tryCatcher (/home/dnick/node_modules/bluebird/js/release/util.js:16:23)
ERR! listen     at Function.Promise.attempt.Promise.try (/home/dnick/node_modules/bluebird/js/release/method.js:39:29)
ERR! listen     at /home/dnick/node_modules/facebook-chat-api/utils.js:989:24
ERR! listen     at tryCatcher (/home/dnick/node_modules/bluebird/js/release/util.js:16:23)
ERR! listen     at Promise._settlePromiseFromHandler (/home/dnick/node_modules/bluebird/js/release/promise.js:547:31)
ERR! listen     at Promise._settlePromise (/home/dnick/node_modules/bluebird/js/release/promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (/home/dnick/node_modules/bluebird/js/release/promise.js:649:10)
ERR! listen     at Promise._settlePromises (/home/dnick/node_modules/bluebird/js/release/promise.js:729:18)
ERR! listen     at Promise._fulfill (/home/dnick/node_modules/bluebird/js/release/promise.js:673:18)
ERR! listen     at Promise._resolveCallback (/home/dnick/node_modules/bluebird/js/release/promise.js:466:57)
ERR! listen     at Promise._settlePromiseFromHandler (/home/dnick/node_modules/bluebird/js/release/promise.js:559:17)
ERR! listen     at Promise._settlePromise (/home/dnick/node_modules/bluebird/js/release/promise.js:604:18)
ERR! listen     at Promise._settlePromise0 (/home/dnick/node_modules/bluebird/js/release/promise.js:649:10)
ERR! listen     at Promise._settlePromises (/home/dnick/node_modules/bluebird/js/release/promise.js:729:18)
ERR! listen     at Promise._fulfill (/home/dnick/node_modules/bluebird/js/release/promise.js:673:18)
Unhandled rejection TypeError: Cannot read property 'body' of undefined
    at api.listen (/home/dnick/Desktop/start.js:8:33)
    at /home/dnick/node_modules/facebook-chat-api/src/listen.js:536:11
    at tryCatcher (/home/dnick/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dnick/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/dnick/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/dnick/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/dnick/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/dnick/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/dnick/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/dnick/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/dnick/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

Any ideas?

**Comment by noeRls** [comment]
This may be related to #820
