### ISSUE TITLE
esockettimedout

### ISSUE THREAD

**Issue by Miho1254** [Schmavery/facebook-chat-api#888]
ERR! markAsDelivered Error: ESOCKETTIMEDOUT
ERR! markAsDelivered     at ClientRequest.<anonymous> (D:\myPrshvnxLDE9Jsm8sJxPxct425HhQC2tk5CVyouDAn3quest\request.js:816:19)
ERR! markAsDelivered     at Object.onceWrapper (node:events:513:28)
ERR! markAsDelivered     at ClientRequest.emit (node:events:394:28)
ERR! markAsDelivered     at TLSSocket.emitRequestTimeout (node:_http_client:761:9)
ERR! markAsDelivered     at Object.onceWrapper (node:events:513:28)
ERR! markAsDelivered     at TLSSocket.emit (node:events:406:35)
ERR! markAsDelivered     at TLSSocket.Socket._onTimeout (node:net:486:8)
ERR! markAsDelivered     at listOnTimeout (node:internal/timers:557:17)
ERR! markAsDelivered     at processTimers (node:internal/timers:500:7)
ERR! markAsDelivered  OperationalError: ESOCKETTIMEDOUT
ERR! markAsDelivered     at ClientRequest.<anonymous> (D:\myPrshvnxLDE9Jsm8sJxPxct425HhQC2tk5CVyouDAn3quest\request.js:816:19)
ERR! markAsDelivered     at Object.onceWrapper (node:events:513:28)
ERR! markAsDelivered     at ClientRequest.emit (node:events:394:28)
ERR! markAsDelivered     at TLSSocket.emitRequestTimeout (node:_http_client:761:9)
ERR! markAsDelivered     at Object.onceWrapper (node:events:513:28)
ERR! markAsDelivered     at TLSSocket.emit (node:events:406:35)
ERR! markAsDelivered     at TLSSocket.Socket._onTimeout (node:net:486:8)
ERR! markAsDelivered     at listOnTimeout (node:internal/timers:557:17)
ERR! markAsDelivered     at processTimers (node:internal/timers:500:7) {
ERR! markAsDelivered   cause: Error: ESOCKETTIMEDOUT
ERR! markAsDelivered       at ClientRequest.<anonymous> (D:\myPrshvnxLDE9Jsm8sJxPxct425HhQC2tk5CVyouDAn3quest\request.js:816:19)
ERR! markAsDelivered       at Object.onceWrapper (node:events:513:28)
ERR! markAsDelivered       at ClientRequest.emit (node:events:394:28)
ERR! markAsDelivered       at TLSSocket.emitRequestTimeout (node:_http_client:761:9)
ERR! markAsDelivered       at Object.onceWrapper (node:events:513:28)
ERR! markAsDelivered       at TLSSocket.emit (node:events:406:35)
ERR! markAsDelivered       at TLSSocket.Socket._onTimeout (node:net:486:8)
ERR! markAsDelivered       at listOnTimeout (node:internal/timers:557:17)
ERR! markAsDelivered       at processTimers (node:internal/timers:500:7) {
ERR! markAsDelivered     code: 'ESOCKETTIMEDOUT',
ERR! markAsDelivered     connect: false
ERR! markAsDelivered   },
ERR! markAsDelivered   isOperational: true,
ERR! markAsDelivered   code: 'ESOCKETTIMEDOUT',
ERR! markAsDelivered   connect: false
ERR! markAsDelivered }
ERR! Error: ESOCKETTIMEDOUT

i got this problem, please help!

**Comment by r1bnc** [comment]
Implement rate limit?
