### ISSUE TITLE
Problem parsing message object and 100% issue

### ISSUE THREAD

**Issue by FuryCSProducer** [Schmavery/facebook-chat-api#889]
error: 'Problem parsing message object. Please open an issue at https://github.com/Schmavery/facebook-chat-api/issues.',
  detail: TypeError: Cannot read property 'id' of null
      at _formatAttachment (/home/container/node_modules/fca-unofficial/utils.js:520:27)
      at /home/container/node_modules/fca-unofficial/utils.js:699:55
      at Array.map (<anonymous>)
      at Object.formatDeltaMessage (/home/container/node_modules/fca-unofficial/utils.js:699:46)
      at resolveAttachmentUrl (/home/container/node_modules/fca-unofficial/src/listenMqtt.js:230:26)
      at resolveAttachmentUrl (/home/container/node_modules/fca-unofficial/src/listenMqtt.js:263:18)
      at parseDelta (/home/container/node_modules/fca-unofficial/src/listenMqtt.js:266:7)
      at MqttClient.<anonymous> (/home/container/node_modules/fca-unofficial/src/listenMqtt.js:182:9)
      at MqttClient.emit (events.js:376:20)
      at MqttClient.emit (domain.js:470:12)
      at Arguments.<anonymous> (/home/container/node_modules/mqtt/lib/client.js:1150:27)
      at Object.MqttClient.options.customHandleAcks (/home/container/node_modules/mqtt/lib/client.js:152:150)
      at MqttClient._handlePublish (/home/container/node_modules/mqtt/lib/client.js:1143:15)
      at MqttClient._handlePacket (/home/container/node_modules/mqtt/lib/client.js:351:12)
      at work (/home/container/node_modules/mqtt/lib/client.js:283:12)
      at Writable.writable._write (/home/container/node_modules/mqtt/lib/client.js:294:5)
      at doWrite (/home/container/node_modules/readable-stream/lib/_stream_writable.js:428:64)
      at writeOrBuffer (/home/container/node_modules/readable-stream/lib/_stream_writable.js:417:5)
      at Writable.write (/home/container/node_modules/readable-stream/lib/_stream_writable.js:334:11)
      at Duplexify.ondata (/home/container/node_modules/readable-stream/lib/_stream_readable.js:619:20)
      at Duplexify.emit (events.js:376:20)
      at Duplexify.emit (domain.js:470:12)
      at addChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at Duplexify.Readable.push (/home/container/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at Duplexify._forward (/home/container/node_modules/duplexify/index.js:170:26)
      at Transform.onreadable (/home/container/node_modules/duplexify/index.js:134:10)
      at Transform.emit (events.js:376:20)
      at Transform.emit (domain.js:470:12)
      at emitReadable_ (/home/container/node_modules/readable-stream/lib/_stream_readable.js:504:10)
      at emitReadable (/home/container/node_modules/readable-stream/lib/_stream_readable.js:498:62)
      at addChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:298:29)
      at readableAddChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at Transform.Readable.push (/home/container/node_modules/readable-stream/lib/_stream_readable.js:245:10),
  res: {
    delta: {
      attachments: [Array],
      data: {},
      irisSeqId: '82128611',
      irisTags: [],
      messageMetadata: [Object],
      participants: [Array],
      requestContext: [Object],
      stickerId: '156924879841673',
      tqSeqId: '1140352',
      class: 'NewMessage'
    }
  },
  type: 'parse_error'
}

**Comment by lv185039** [comment]
Does the message object contain any attachments or anything unusual?
