### ISSUE TITLE
 Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by bearbear12345** [Schmavery/facebook-chat-api#89]
Application crashing on ``` switch (event.type) {``` even though ```type``` exists in the message data

```
Unhandled rejection TypeError: Cannot read property 'type' of undefined
    at callback (/home/usrt/fbchatapi/fbcl.js:45:18)
    at /home/usrt/fbchatapi/node_modules/facebook-chat-api/src/listen.js:212:7
    at tryCatcher (/home/usrt/fbchatapi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/usrt/fbchatapi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/usrt/fbchatapi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/usrt/fbchatapi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/usrt/fbchatapi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/usrt/fbchatapi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/usrt/fbchatapi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by Schmavery** [comment]
Is this happening with all messages that get passed to the listen callback or just in certain cases?  Is it possible for you to show us a code sample that exhibits this behaviour?

**Comment by bsansouci** [comment]
Also can you give us steps to reproduce this?

**Comment by bearbear12345** [comment]
It seems like it happens after receiving a message after a period of inactivity?

With options
```
logLevel: "silent"
selfListen: true
listenEvents: true
```

```
api.listen(function (err, event) {
  fs.appendFile('debug.log', JSON.stringify(event), function(){});
  ... do stuff ...
});
```

I temporarily resolved this by ignoring the undefined event, but I'd like to know why it happens
```
  if (typeof event !== "undefined") {
    ... do stuff ...
  }
```

The debug.log I used showed something along the lines of
```{stuff containing the message json}
{stuff containing the message json}
{stuff containing the message json}
undefined
```

**Comment by Schmavery** [comment]
Just a thought... I assume the error in null in these cases?

**Comment by bearbear12345** [comment]
Ahh right, I'll go and debug print both arguments.

**Comment by bearbear12345** [comment]
Here we are

```
{ error: 'JSON.parse error. Check the `detail` property on this error.',
  detail: [SyntaxError: Unexpected token <],
  res: '<!DOCTYPE html>\n<html lang="en" id="facebook">\n  <head>\n    <title>Facebook | Error</title>\n    <meta charset="utf-8">\n    <meta http-equiv="cache-control" content="no-cache">\n    <meta http-equiv="cache-control" content="no-store">\n    <meta http-equiv="cache-control" content="max-age=0">\n    <meta http-equiv="expires" content="-1">\n    <meta http-equiv="pragma" content="no-cache">\n    <meta name="robots" content="noindex,nofollow">\n    <style>\n      html, body {\n        color: #141823;\n        background-color: #e9eaed;\n        font-family: Helvetica, Lucida Grande, Arial,\n                     Tahoma, Verdana, sans-serif;\n        margin: 0;\n        padding: 0;\n        text-align: center;\n      }\n\n      #header {\n        height: 30px;\n        padding-bottom: 10px;\n        padding-top: 10px;\n        text-align: center;\n      }\n\n      #icon {\n        width: 30px;\n      }\n\n      h1 {\n        font-size: 18px;\n      }\n\n      p {\n        font-size: 13px;\n      }\n\n      #footer {\n        border-top: 1px solid #ddd;\n        color: #9197a3;\n        font-size: 12px;\n        padding: 5px 8px 6px 0;\n      }\n    </style>\n  </head>\n  <body>\n    <div id="header">\n      <a href="//www.facebook.com/">\n        <img id="icon" src="//static.xx.fbcdn.net/images/logos/facebook_2x.png" />\n      </a>\n    </div>\n    <div id="core">\n      <h1 id="sorry">Sorry, something went wrong.</h1>\n      <p id="promise">\n        We\'re working on it and we\'ll get it fixed as soon as we can.\n      </p>\n      <p id="back-link">\n        <a id="back" href="//www.facebook.com/">Go Back</a>\n      </p>\n      <div id="footer">\n        Facebook\n        <span id="copyright">\n          &copy; 2015\n        </span>\n        <span id="help-link">\n          &#183;\n          <a id="help" href="//www.facebook.com/help/">Help Center</a>\n        </span>\n      </div>\n    </div>\n    <script>\n      document.getElementById(\'back\').onclick = function() {\n        if (history.length > 1) {\n          history.back();\n          return false;\n        }\n      };\n\n      // Adjust the display based on the window size\n      if (window.innerHeight < 80 || window.innerWidth < 80) {\n        // Blank if window is too small\n        document.body.style.display = \'none\';\n      };\n      if (window.innerWidth < 200 || window.innerHeight < 150) {\n        document.getElementById(\'back-link\').style.display = \'none\';\n        document.getElementById(\'help-link\').style.display = \'none\';\n      };\n      if (window.innerWidth < 200) {\n        document.getElementById(\'sorry\').style.fontSize = \'16px\';\n      };\n      if (window.innerWidth < 150) {\n        document.getElementById(\'promise\').style.display = \'none\';\n      };\n      if (window.innerHeight < 150) {\n        document.getElementById(\'sorry\').style.margin = \'4px 0 0 0\';\n        document.getElementById(\'sorry\').style.fontSize = \'14px\';\n        document.getElementById(\'promise\').style.display = \'none\';\n      };\n    </script>\n  </body>\n</html>\n' }
```

Two of those errors were printed during my (unattended) debug (didn't record the time, whoops)

**Comment by Schmavery** [comment]
You say "after a period of inactivity"... how long are we talking?  Here it looks like facebook has logged you out (or at least gotten confused), in which case logging in again should fix the problem.

**Comment by Schmavery** [comment]
As far as I can tell, considering an error was sent, this is expected behaviour.  The only question here is whether we should suppress the callback in failure cases such as these. @bsansouci ?
If after receiving this error, you continue to receive valid messages/events, then I think we should not call the callback with this error.  However, if this error indicates that there is a deeper problem, we obviously shouldn't just hide it.  Hopefully @bearbear12345 can offer some insight into which is the case.

**Comment by bearbear12345** [comment]
Hi, I've only gotten this error once, during my logging period
```
{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false}
```
at epoch 1447576341

There weren't any messages near that time

-----------

Messages also continue to be received after the error

**Comment by Schmavery** [comment]
@bsansouci Can we suppress these ETIMEDOUT errors or do you think we should force users to handle them?

**Comment by bsansouci** [comment]
I'm not sure why those appear. We can suppress them for now.

**Comment by bearbear12345** [comment]
So like @lasseborly referenced, I, too am also getting that issue.
Decided to turn on 'silly' logging today, and got the same thing

```
info Got answer in  252
ERR! ERROR in listen -->  TypeError: Cannot read property 'toString' of undefined
ERR! ERROR in listen -->      at Object.formatTyp (/root/Applications/fbchatlog/node_modules/facebook-chat-api/utils.js:294:46)
ERR! ERROR in listen -->      at parsePackets (/root/Applications/fbchatlog/node_modules/facebook-chat-api/src/listen.js:112:42)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /root/Applications/fbchatlog/node_modules/facebook-chat-api/src/listen.js:101:12
ERR! ERROR in listen -->      at tryCatcher (/root/Applications/fbchatlog/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/root/Applications/fbchatlog/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/root/Applications/fbchatlog/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/root/Applications/fbchatlog/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (/root/Applications/fbchatlog/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/root/Applications/fbchatlog/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (/root/Applications/fbchatlog/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

#runasroot

**Comment by bsansouci** [comment]
This really doesn't seem like the same error.  This is a very specific problem where Facebook sends us a timeout error for no reason.  This actually isn't really a problem with the API.
Your issue is handled by #110.
