### ISSUE TITLE
TypeError: Cannot read property 'caption' of undefined when sending a thumbs-up via Chat

### ISSUE THREAD

**Issue by pandalion98** [Schmavery/facebook-chat-api#91]
ERR! ERROR in listen -->  TypeError: Cannot read property 'caption' of undefined
   at _formatAttachment (/home/pi/node_modules/facebook-chat-api/utils.js:155:31)
   at /home/pi/node_modules/facebook-chat-api/utils.js:250:12
   at Array.map (native)
   at formatAttachment (/home/pi/node_modules/facebook-chat-api/utils.js:245:36)
   at Object.formatMessage (/home/pi/node_modules/facebook-chat-api/utils.js:267:18)
   at parsePackets (/home/pi/node_modules/facebook-chat-api/src/listen.js:134:35)
   at Array.forEach (native)
   at /home/pi/node_modules/facebook-chat-api/src/listen.js:86:12
   at tryCatcher (/home/pi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
   at Promise._settlePromiseFromHandler (/home/pi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
   at Promise._settlePromiseAt (/home/pi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
   at Promise._settlePromises (/home/pi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
   at Async._drainQueue (/home/pi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
   at Async._drainQueues (/home/pi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
   at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
   at processImmediate [as _immediateCallback] (timers.js:368:17)
[TypeError: Cannot read property 'caption' of undefined]

**Comment by bsansouci** [comment]
Hey @pandalion98 can you check if ae5191121e5a967cc294b22b4dc08414f6ceb349 fixes it?

**Comment by pandalion98** [comment]
Let me check.

**Comment by Schmavery** [comment]
If this doesn't fix the problem, can you clarify which type of thumbs-up you're talking about?  Afaik there are 3 kinds:
![image](https://cloud.githubusercontent.com/assets/2154522/10932324/bd0e8688-8284-11e5-9018-8f9e287c608d.png)
Can you tell us which one is causing the problem?

**Comment by pandalion98** [comment]
Second one.

**Comment by pandalion98** [comment]
ae51911 fixed it.
